## 00-1. Preprocessing (CPTAC-LUAD)

In [1]:
library(data.table)
library(vespa)

In [2]:
if (!dir.exists("./data/cptac-luad")) {
  out <- system2(
    "bash",
    "./tools/scripts/cptac-luad.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

In [3]:
if (!file.exists("./tools/references/library.fasta")) {
  out <- system2(
    "bash",
    "./tools/scripts/fasta.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

## Import data

In [4]:
phospho <- importPhosphoCPTAC(
    "./data/cptac-luad/CPTAC3_Lung_Adeno_Carcinoma_Phosphoproteome.phosphopeptide.tmt10.tsv",
    fasta="./tools/references/library.fasta",
    cores=6
)
phospho

Loading FASTA DB

Loading CPTAC data

Mapping CPTAC peptides to FASTA

Mapping phosphopeptide sites

        gene_id protein_id peptide_id site_id
1       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
2       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
3       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
4       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
5       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
6       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
7       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
8       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
9       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
10      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
11      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
12      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
13      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
14      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
15      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
16      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
17      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
18      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
19      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
20      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
21      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
22      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
23      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
24      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
25      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
26      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
27      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
28      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
29      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
30      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
⋮       ⋮       ⋮          ⋮          ⋮
3432890 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
3432891 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
3432892 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
3432893 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
3432894 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
3432895 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
3432896 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
3432897 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
3432898 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
3432899 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
3432900 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
3432901 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
3432902 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432903 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
3432904 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432905 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
3432906 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432907 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
3432908 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432909 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
3432910 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432911 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
3432912 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432913 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
3432914 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432915 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
3432916 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432917 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
3432918 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
3432919 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
        modified_peptide_sequence    peptide_sequence             phosphosite
1       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
2       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
3       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
4       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
5       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
6       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
7       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
8       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
9       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
10      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
11      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
12      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
13      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
14      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
15      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
16      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
17      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
18      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
19      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
20      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
21      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
22      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
23      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
24      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
25      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
26      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
27      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
28      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
29      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
30      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
⋮       ⋮                            ⋮                            ⋮
3432890 ysRSPAR                      YSRSPAR                      S454
3432891 ysRSPAR                      YSRSPAR                      Y453
3432892 ysRSPAR                      YSRSPAR                      S454
3432893 ysRSPAR                      YSRSPAR                      Y453
3432894 ysRSPAR                      YSRSPAR                      S454
3432895 ysRSPAR                      YSRSPAR                      Y453
3432896 ysRSPAR                      YSRSPAR                      S454
3432897 ysRSPAR                      YSRSPAR                      Y453
3432898 ysRSPAR                      YSRSPAR                      S454
3432899 ysRSPAR                      YSRSPAR                      Y453
3432900 ysRSPAR                      YSRSPAR                      S454
3432901 ysRSPAR                      YSRSPAR                      Y453
3432902 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432903 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
3432904 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432905 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
3432906 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432907 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
3432908 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432909 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
3432910 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432911 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
3432912 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432913 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
3432914 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432915 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
3432916 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432917 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
3432918 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
3432919 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
        run_id          peptide_intensity
1       CPT0118340003    1.15395718
2       CPT0118360003   -1.78267469
3       CPT0110860004    0.08227344
4       CPT0110890003   -0.88318899
5       CPT0083780003    0.24364525
6       CPT0083810003   -0.75153047
7       CPT0069700003    1.52308965
8       CPT0069720003   -1.13333605
9       CPT0053040004    1.39954928
10      CPT0109680004    0.37027238
11      CPT0109700003   -1.62530627
12      CPT0105940003    0.39422096
13      CPT0105980003   -1.76016006
14      CPT0090170004    0.86323399
15      CPT0090200003   -1.96373444
16      CPT0105330003    1.81565590
17      CPT0105370004   -1.32976834
18      CPT0148080004.2 -0.63457780
19      CPT0105710003    0.92679021
20      CPT0105740003   -1.57967613
21      CPT0118620003    0.01088396
22      CPT0118650003   -1.43863162
23      CPT0147080004    1.32073921
24      CPT0147100003   -1.50688952
25      CPT0082740004    0.36175463
26      CPT0082770003   -0.97413235
27      CPT0146580004.1  1.24919369
28      CPT0104970003    0.07487876
29      CPT0105010004   -0.99776831
30      CPT0090340003    3.34039488
⋮       ⋮               ⋮
3432890 CPT0097600003    0.63747190
3432891 CPT0097600003    0.63747190
3432892 CPT0113210003    0.07878603
3432893 CPT0113210003    0.07878603
3432894 CPT0113220003    0.25907988
3432895 CPT0113220003    0.25907988
3432896 CPT0114840003    0.53480739
3432897 CPT0114840003    0.53480739
3432898 CPT0114880003    0.43790056
3432899 CPT0114880003    0.43790056
3432900 NormalOnlyIR.4  -0.18703769
3432901 NormalOnlyIR.4  -0.18703769
3432902 CPT0148080004.1  0.49851594
3432903 CPT0148080004.1  0.49851594
3432904 CPT0148100003   -0.49117404
3432905 CPT0148100003   -0.49117404
3432906 CPT0083100003    0.49654626
3432907 CPT0083100003    0.49654626
3432908 CPT0083140003   -0.26688943
3432909 CPT0083140003   -0.26688943
3432910 CPT0118160003    1.04963344
3432911 CPT0118160003    1.04963344
3432912 CPT0118180003   -1.54306163
3432913 CPT0118180003   -1.54306163
3432914 CPT0105510003    1.05259038
3432915 CPT0105510003    1.05259038
3432916 CPT0105550003   -0.09836768
3432917 CPT0105550003   -0.09836768
3432918 TumorOnlyIR.2    0.35818374
3432919 TumorOnlyIR.2    0.35818374

In [5]:
proteo <- importProteoCPTAC(
    "./data/cptac-luad/CPTAC3_Lung_Adeno_Carcinoma_Proteome.tmt10.tsv",
    fasta="./tools/references/library.fasta"
)
proteo

Loading FASTA DB

Loading CPTAC data

        gene_id  protein_id peptide_id site_id
1       A1BG     P04217     P04217     A1BG:P04217:PA
2       A1CF     Q9NQ94     Q9NQ94     A1CF:Q9NQ94:PA
3       A2M      P01023     P01023     A2M:P01023:PA
4       AAAS     Q9NRG9     Q9NRG9     AAAS:Q9NRG9:PA
5       AACS     Q86V21     Q86V21     AACS:Q86V21:PA
6       AADAC    P22760     P22760     AADAC:P22760:PA
7       AADAT    Q8N5Z0     Q8N5Z0     AADAT:Q8N5Z0:PA
8       AAGAB    Q6PD74     Q6PD74     AAGAB:Q6PD74:PA
9       AAK1     Q2M2I8     Q2M2I8     AAK1:Q2M2I8:PA
10      AAMDC    Q9H7C9     Q9H7C9     AAMDC:Q9H7C9:PA
11      AAMP     Q13685     Q13685     AAMP:Q13685:PA
12      AAR2     Q9Y312     Q9Y312     AAR2:Q9Y312:PA
13      AARS     P49588     P49588     AARS:P49588:PA
14      AARS2    Q5JTZ9     Q5JTZ9     AARS2:Q5JTZ9:PA
15      AARSD1   Q9BTE6     Q9BTE6     AARSD1:Q9BTE6:PA
16      AASDHPPT Q9NRN7     Q9NRN7     AASDHPPT:Q9NRN7:PA
17      AASS     Q9UDR5     Q9UDR5     AASS:Q9UDR5:PA
18      AATF     Q9NY61     Q9NY61     AATF:Q9NY61:PA
19      AATK     Q6ZMQ8     Q6ZMQ8     AATK:Q6ZMQ8:PA
20      ABAT     P80404     P80404     ABAT:P80404:PA
21      ABCA1    O95477     O95477     ABCA1:O95477:PA
22      ABCA12   Q86UK0     Q86UK0     ABCA12:Q86UK0:PA
23      ABCA2    Q9BZC7     Q9BZC7     ABCA2:Q9BZC7:PA
24      ABCA3    Q99758     Q99758     ABCA3:Q99758:PA
25      ABCA6    Q8N139     Q8N139     ABCA6:Q8N139:PA
26      ABCA7    Q8IZY2     Q8IZY2     ABCA7:Q8IZY2:PA
27      ABCA8    O94911     O94911     ABCA8:O94911:PA
28      ABCB1    P08183     P08183     ABCB1:P08183:PA
29      ABCB10   Q9NRK6     Q9NRK6     ABCB10:Q9NRK6:PA
30      ABCB6    Q9NP58     Q9NP58     ABCB6:Q9NP58:PA
⋮       ⋮        ⋮          ⋮          ⋮
2452921 ZNF845   Q96IR2     Q96IR2     ZNF845:Q96IR2:PA
2452922 ZNF852   Q6ZMS4     Q6ZMS4     ZNF852:Q6ZMS4:PA
2452923 ZNF865   P0CJ78     P0CJ78     ZNF865:P0CJ78:PA
2452924 ZNF91    Q05481     Q05481     ZNF91:Q05481:PA
2452925 ZNFX1    Q9P2E3     Q9P2E3     ZNFX1:Q9P2E3:PA
2452926 ZNHIT1   O43257     O43257     ZNHIT1:O43257:PA
2452927 ZNHIT2   Q9UHR6     Q9UHR6     ZNHIT2:Q9UHR6:PA
2452928 ZNHIT3   Q15649     Q15649     ZNHIT3:Q15649:PA
2452929 ZNHIT6   Q9NWK9     Q9NWK9     ZNHIT6:Q9NWK9:PA
2452930 ZNRD1    Q9P1U0     Q9P1U0     ZNRD1:Q9P1U0:PA
2452931 ZNRF1    Q8ND25     Q8ND25     ZNRF1:Q8ND25:PA
2452932 ZNRF2    Q8NHG8     Q8NHG8     ZNRF2:Q8NHG8:PA
2452933 ZPR1     O75312     O75312     ZPR1:O75312:PA
2452934 ZRANB2   O95218     O95218     ZRANB2:O95218:PA
2452935 ZRSR2    Q15696     Q15696     ZRSR2:Q15696:PA
2452936 ZSCAN18  Q8TBC5     Q8TBC5     ZSCAN18:Q8TBC5:PA
2452937 ZSCAN26  Q16670     Q16670     ZSCAN26:Q16670:PA
2452938 ZSCAN31  Q96LW9     Q96LW9     ZSCAN31:Q96LW9:PA
2452939 ZSWIM4   Q9H7M6     Q9H7M6     ZSWIM4:Q9H7M6:PA
2452940 ZSWIM8   A7E2V4     A7E2V4     ZSWIM8:A7E2V4:PA
2452941 ZSWIM9   Q86XI8     Q86XI8     ZSWIM9:Q86XI8:PA
2452942 ZW10     O43264     O43264     ZW10:O43264:PA
2452943 ZWILCH   Q9H900     Q9H900     ZWILCH:Q9H900:PA
2452944 ZWINT    O95229     O95229     ZWINT:O95229:PA
2452945 ZXDA     P98168     P98168     ZXDA:P98168:PA
2452946 ZXDC     Q2QGD7     Q2QGD7     ZXDC:Q2QGD7:PA
2452947 ZYG11B   Q9C0D3     Q9C0D3     ZYG11B:Q9C0D3:PA
2452948 ZYX      Q15942     Q15942     ZYX:Q15942:PA
2452949 ZZEF1    O43149     O43149     ZZEF1:O43149:PA
2452950 ZZZ3     Q8IYH5     Q8IYH5     ZZZ3:Q8IYH5:PA
        modified_peptide_sequence peptide_sequence phosphosite run_id
1       P04217                    P04217           PA          CPT0089340003
2       Q9NQ94                    Q9NQ94           PA          CPT0089340003
3       P01023                    P01023           PA          CPT0089340003
4       Q9NRG9                    Q9NRG9           PA          CPT0089340003
5       Q86V21                    Q86V21           PA          CPT0089340003
6       P22760                    P22760           PA          CPT0089340003
7       Q8N5Z0                    Q8N5Z0           PA          CPT0089340003
8       Q6PD74                    Q6PD74           PA          CPT0089340003
9       Q2M2I8                    Q2M2I8           PA          CPT0089340003
10      Q9H7C9                    Q9H7C9           PA          CPT0089340003
11      Q13685                    Q13685           PA          CPT0089340003
12      Q9Y312                    Q9Y312           PA          CPT0089340003
13      P49588                    P49588           PA          CPT0089340003
14      Q5JTZ9                    Q5JTZ9           PA          CPT0089340003
15      Q9BTE6                    Q9BTE6           PA          CPT0089340003
16      Q9NRN7                    Q9NRN7           PA          CPT0089340003
17      Q9UDR5                    Q9UDR5           PA          CPT0089340003
18      Q9NY61                    Q9NY61           PA          CPT0089340003
19      Q6ZMQ8                    Q6ZMQ8           PA          CPT0089340003
20      P80404                    P80404           PA          CPT0089340003
21      O95477                    O95477           PA          CPT0089340003
22      Q86UK0                    Q86UK0           PA          CPT0089340003
23      Q9BZC7                    Q9BZC7           PA          CPT0089340003
24      Q99758                    Q99758           PA          CPT0089340003
25      Q8N139                    Q8N139           PA          CPT0089340003
26      Q8IZY2                    Q8IZY2           PA          CPT0089340003
27      O94911                    O94911           PA          CPT0089340003
28      P08183                    P08183           PA          CPT0089340003
29      Q9NRK6                    Q9NRK6           PA          CPT0089340003
30      Q9NP58                    Q9NP58           PA          CPT0089340003
⋮       ⋮                         ⋮                ⋮           ⋮
2452921 Q96IR2                    Q96IR2           PA          NormalOnlyIR.4
2452922 Q6ZMS4                    Q6ZMS4           PA          NormalOnlyIR.4
2452923 P0CJ78                    P0CJ78           PA          NormalOnlyIR.4
2452924 Q05481                    Q05481           PA          NormalOnlyIR.4
2452925 Q9P2E3                    Q9P2E3           PA          NormalOnlyIR.4
2452926 O43257                    O43257           PA          NormalOnlyIR.4
2452927 Q9UHR6                    Q9UHR6           PA          NormalOnlyIR.4
2452928 Q15649                    Q15649           PA          NormalOnlyIR.4
2452929 Q9NWK9                    Q9NWK9           PA          NormalOnlyIR.4
2452930 Q9P1U0                    Q9P1U0           PA          NormalOnlyIR.4
2452931 Q8ND25                    Q8ND25           PA          NormalOnlyIR.4
2452932 Q8NHG8                    Q8NHG8           PA          NormalOnlyIR.4
2452933 O75312                    O75312           PA          NormalOnlyIR.4
2452934 O95218                    O95218           PA          NormalOnlyIR.4
2452935 Q15696                    Q15696           PA          NormalOnlyIR.4
2452936 Q8TBC5                    Q8TBC5           PA          NormalOnlyIR.4
2452937 Q16670                    Q16670           PA          NormalOnlyIR.4
2452938 Q96LW9                    Q96LW9           PA          NormalOnlyIR.4
2452939 Q9H7M6                    Q9H7M6           PA          NormalOnlyIR.4
2452940 A7E2V4                    A7E2V4           PA          NormalOnlyIR.4
2452941 Q86XI8                    Q86XI8           PA          NormalOnlyIR.4
2452942 O43264                    O43264           PA          NormalOnlyIR.4
2452943 Q9H900                    Q9H900           PA          NormalOnlyIR.4
2452944 O95229                    O95229           PA          NormalOnlyIR.4
2452945 P98168                    P98168           PA          NormalOnlyIR.4
2452946 Q2QGD7                    Q2QGD7           PA          NormalOnlyIR.4
2452947 Q9C0D3                    Q9C0D3           PA          NormalOnlyIR.4
2452948 Q15942                    Q15942           PA          NormalOnlyIR.4
2452949 O43149                    O43149           PA          NormalOnlyIR.4
2452950 Q8IYH5                    Q8IYH5           PA          NormalOnlyIR.4
        peptide_intensity
1       -0.608178218
2                 NA
3       -0.852777619
4        0.063600148
5       -0.124289958
6       -2.281265494
7       -0.869112802
8       -0.091862293
9       -0.002046645
10       0.175400585
11       0.339276762
12       0.021640839
13       0.255146168
14      -0.150221550
15       0.358136801
16       0.386885484
17       0.209195785
18       0.775807351
19      -0.438669789
20       0.500467253
21      -0.444890962
22                NA
23       0.467599205
24      -1.556549386
25      -0.233133122
26       0.095722294
27      -0.698130760
28      -0.182074489
29       0.843830594
30       0.098256078
⋮       ⋮
2452921 -0.20109283
2452922  0.15132910
2452923  0.20000349
2452924  0.53714645
2452925 -0.13439134
2452926 -0.25802305
2452927 -0.25889564
2452928 -0.64448856
2452929  0.02370994
2452930 -0.22629284
2452931          NA
2452932 -0.39425773
2452933 -0.36553236
2452934 -0.25503582
2452935 -0.76627947
2452936  0.01324926
2452937  0.02676684
2452938 -0.33076450
2452939          NA
2452940  0.01046398
2452941  0.18753392
2452942 -0.13183501
2452943 -1.03084618
2452944          NA
2452945          NA
2452946  0.86513129
2452947  0.07386401
2452948  0.40129448
2452949  0.13473647
2452950  0.17996214

In [6]:
clin <- fread("./data/cptac-luad/S046_Lung_Adenocarcinoma.csv")
clin

      Dataset    Run                                               Cohort
1     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Lung Cancer
2     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Normal
3     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Lung Cancer
4     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Normal
5     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Lung Cancer
6     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Normal
7     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Lung Cancer
8     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Normal
9     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Tumor Norm
10    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Norm
11    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Lung Cancer
12    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Normal
13    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Lung Cancer
14    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Normal
15    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Lung Cancer
16    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Normal
17    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Lung Cancer
18    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Normal
19    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Tumor Norm
20    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Norm
21    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Lung Cancer
22    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Normal
23    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Lung Cancer
24    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Normal
25    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Lung Cancer
26    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Normal
27    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Lung Cancer
28    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Normal
29    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Tumor Norm
30    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Norm
⋮     ⋮          ⋮                                                 ⋮
12151 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Lung Cancer
12152 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal
12153 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Lung Cancer
12154 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal
12155 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Lung Cancer
12156 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal
12157 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Lung Cancer
12158 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal
12159 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal Norm
12160 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Norm
12161 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Lung Cancer
12162 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal
12163 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Lung Cancer
12164 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal
12165 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Lung Cancer
12166 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal
12167 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Lung Cancer
12168 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal
12169 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal Norm
12170 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Norm
12171 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Lung Cancer
12172 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal
12173 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Lung Cancer
12174 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal
12175 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Lung Cancer
12176 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal
12177 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Lung Cancer
12178 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal
12179 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal Norm
12180 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Norm
      Subject           Condition   TimePoint BioReplicate Experiment Mixture
1     Patient_C3N-01799 Lung Cancer NA        1            1          1
2     Patient_C3N-01799 Normal      NA        1            1          1
3     Patient_C3L-01890 Lung Cancer NA        2            2          1
4     Patient_C3L-01890 Normal      NA        2            2          1
5     Patient_C3N-00572 Lung Cancer NA        3            3          1
6     Patient_C3N-00572 Normal      NA        3            3          1
7     Patient_C3N-02423 Lung Cancer NA        4            4          1
8     Patient_C3N-02423 Normal      NA        4            4          1
9     Tumor Norm        Tumor Norm  NA        1            1          1
10    Norm              Norm        NA        Norm         Norm       1
11    Patient_C3N-01799 Lung Cancer NA        1            1          1
12    Patient_C3N-01799 Normal      NA        1            1          1
13    Patient_C3L-01890 Lung Cancer NA        2            2          1
14    Patient_C3L-01890 Normal      NA        2            2          1
15    Patient_C3N-00572 Lung Cancer NA        3            3          1
16    Patient_C3N-00572 Normal      NA        3            3          1
17    Patient_C3N-02423 Lung Cancer NA        4            4          1
18    Patient_C3N-02423 Normal      NA        4            4          1
19    Tumor Norm        Tumor Norm  NA        1            1          1
20    Norm              Norm        NA        Norm         Norm       1
21    Patient_C3N-01799 Lung Cancer NA        1            1          1
22    Patient_C3N-01799 Normal      NA        1            1          1
23    Patient_C3L-01890 Lung Cancer NA        2            2          1
24    Patient_C3L-01890 Normal      NA        2            2          1
25    Patient_C3N-00572 Lung Cancer NA        3            3          1
26    Patient_C3N-00572 Normal      NA        3            3          1
27    Patient_C3N-02423 Lung Cancer NA        4            4          1
28    Patient_C3N-02423 Normal      NA        4            4          1
29    Tumor Norm        Tumor Norm  NA        1            1          1
30    Norm              Norm        NA        Norm         Norm       1
⋮     ⋮                 ⋮           ⋮         ⋮            ⋮          ⋮
12151 Patient_C3N-00175 Lung Cancer NA        110          1          25
12152 Patient_C3N-00175 Normal      NA        99           1          25
12153 Patient_C3N-01823 Lung Cancer NA        111          2          25
12154 Patient_C3N-01823 Normal      NA        100          2          25
12155 Patient_C3L-02549 Lung Cancer NA        112          3          25
12156 Patient_C3L-02549 Normal      NA        101          3          25
12157 Patient_C3L-02365 Lung Cancer NA        113          4          25
12158 Patient_C3L-02365 Normal      NA        102          4          25
12159 Normal Norm       Normal Norm NA        4            1          25
12160 Norm              Norm        NA        Norm         Norm       25
12161 Patient_C3N-00175 Lung Cancer NA        110          1          25
12162 Patient_C3N-00175 Normal      NA        99           1          25
12163 Patient_C3N-01823 Lung Cancer NA        111          2          25
12164 Patient_C3N-01823 Normal      NA        100          2          25
12165 Patient_C3L-02549 Lung Cancer NA        112          3          25
12166 Patient_C3L-02549 Normal      NA        101          3          25
12167 Patient_C3L-02365 Lung Cancer NA        113          4          25
12168 Patient_C3L-02365 Normal      NA        102          4          25
12169 Normal Norm       Normal Norm NA        4            1          25
12170 Norm              Norm        NA        Norm         Norm       25
12171 Patient_C3N-00175 Lung Cancer NA        110          1          25
12172 Patient_C3N-00175 Normal      NA        99           1          25
12173 Patient_C3N-01823 Lung Cancer NA        111          2          25
12174 Patient_C3N-01823 Normal      NA        100          2          25
12175 Patient_C3L-02549 Lung Cancer NA        112          3          25
12176 Patient_C3L-02549 Normal      NA        101          3          25
12177 Patient_C3L-02365 Lung Cancer NA        113          4          25
12178 Patient_C3L-02365 Normal      NA        102          4          25
12179 Normal Norm       Normal Norm NA        4            1          25
12180 Norm              Norm        NA        Norm         Norm       25
      TechRepMixture Batch     Channel Fraction Species        Disease
1     1              Acetylome 126     1        NCBITaxon:9606 DOID:1324
2     1              Acetylome 127N    1        NCBITaxon:9606
3     1              Acetylome 127C    1        NCBITaxon:9606 DOID:1324
4     1              Acetylome 128N    1        NCBITaxon:9606
5     1              Acetylome 128C    1        NCBITaxon:9606 DOID:1324
6     1              Acetylome 129N    1        NCBITaxon:9606
7     1              Acetylome 129C    1        NCBITaxon:9606 DOID:1324
8     1              Acetylome 130N    1        NCBITaxon:9606
9     1              Acetylome 130C    1        NCBITaxon:9606 DOID:1324
10    1              Acetylome 131     1        NCBITaxon:9606
11    1              Acetylome 126     2        NCBITaxon:9606 DOID:1324
12    1              Acetylome 127N    2        NCBITaxon:9606
13    1              Acetylome 127C    2        NCBITaxon:9606 DOID:1324
14    1              Acetylome 128N    2        NCBITaxon:9606
15    1              Acetylome 128C    2        NCBITaxon:9606 DOID:1324
16    1              Acetylome 129N    2        NCBITaxon:9606
17    1              Acetylome 129C    2        NCBITaxon:9606 DOID:1324
18    1              Acetylome 130N    2        NCBITaxon:9606
19    1              Acetylome 130C    2        NCBITaxon:9606 DOID:1324
20    1              Acetylome 131     2        NCBITaxon:9606
21    1              Acetylome 126     3        NCBITaxon:9606 DOID:1324
22    1              Acetylome 127N    3        NCBITaxon:9606
23    1              Acetylome 127C    3        NCBITaxon:9606 DOID:1324
24    1              Acetylome 128N    3        NCBITaxon:9606
25    1              Acetylome 128C    3        NCBITaxon:9606 DOID:1324
26    1              Acetylome 129N    3        NCBITaxon:9606
27    1              Acetylome 129C    3        NCBITaxon:9606 DOID:1324
28    1              Acetylome 130N    3        NCBITaxon:9606
29    1              Acetylome 130C    3        NCBITaxon:9606 DOID:1324
30    1              Acetylome 131     3        NCBITaxon:9606
⋮     ⋮              ⋮         ⋮       ⋮        ⋮              ⋮
12151 1              Proteome  126     23       NCBITaxon:9606 DOID:1324
12152 1              Proteome  127N    23       NCBITaxon:9606
12153 1              Proteome  127C    23       NCBITaxon:9606 DOID:1324
12154 1              Proteome  128N    23       NCBITaxon:9606
12155 1              Proteome  128C    23       NCBITaxon:9606 DOID:1324
12156 1              Proteome  129N    23       NCBITaxon:9606
12157 1              Proteome  129C    23       NCBITaxon:9606 DOID:1324
12158 1              Proteome  130N    23       NCBITaxon:9606
12159 1              Proteome  130C    23       NCBITaxon:9606
12160 1              Proteome  131     23       NCBITaxon:9606
12161 1              Proteome  126     24       NCBITaxon:9606 DOID:1324
12162 1              Proteome  127N    24       NCBITaxon:9606
12163 1              Proteome  127C    24       NCBITaxon:9606 DOID:1324
12164 1              Proteome  128N    24       NCBITaxon:9606
12165 1              Proteome  128C    24       NCBITaxon:9606 DOID:1324
12166 1              Proteome  129N    24       NCBITaxon:9606
12167 1              Proteome  129C    24       NCBITaxon:9606 DOID:1324
12168 1              Proteome  130N    24       NCBITaxon:9606
12169 1              Proteome  130C    24       NCBITaxon:9606
12170 1              Proteome  131     24       NCBITaxon:9606
12171 1              Proteome  126     25       NCBITaxon:9606 DOID:1324
12172 1              Proteome  127N    25       NCBITaxon:9606
12173 1              Proteome  127C    25       NCBITaxon:9606 DOID:1324
12174 1              Proteome  128N    25       NCBITaxon:9606
12175 1              Proteome  128C    25       NCBITaxon:9606 DOID:1324
12176 1              Proteome  129N    25       NCBITaxon:9606
12177 1              Proteome  129C    25       NCBITaxon:9606 DOID:1324
12178 1              Proteome  130N    25       NCBITaxon:9606
12179 1              Proteome  130C    25       NCBITaxon:9606
12180 1              Proteome  131     25       NCBITaxon:9606
      Tissue                  Enzyme     Notes
1     BTO:0000551             MS:1001251 NA
2     BTO:0000763             MS:1001251 NA
3     BTO:0000551             MS:1001251 NA
4     BTO:0000763             MS:1001251 NA
5     BTO:0000551             MS:1001251 NA
6     BTO:0000763             MS:1001251 NA
7     BTO:0000551             MS:1001251 NA
8     BTO:0000763             MS:1001251 NA
9     BTO:0000551             MS:1001251 NA
10    BTO:0000763;BTO:0000551 MS:1001251 NA
11    BTO:0000551             MS:1001251 NA
12    BTO:0000763             MS:1001251 NA
13    BTO:0000551             MS:1001251 NA
14    BTO:0000763             MS:1001251 NA
15    BTO:0000551             MS:1001251 NA
16    BTO:0000763             MS:1001251 NA
17    BTO:0000551             MS:1001251 NA
18    BTO:0000763             MS:1001251 NA
19    BTO:0000551             MS:1001251 NA
20    BTO:0000763;BTO:0000551 MS:1001251 NA
21    BTO:0000551             MS:1001251 NA
22    BTO:0000763             MS:1001251 NA
23    BTO:0000551             MS:1001251 NA
24    BTO:0000763             MS:1001251 NA
25    BTO:0000551             MS:1001251 NA
26    BTO:0000763             MS:1001251 NA
27    BTO:0000551             MS:1001251 NA
28    BTO:0000763             MS:1001251 NA
29    BTO:0000551             MS:1001251 NA
30    BTO:0000763;BTO:0000551 MS:1001251 NA
⋮     ⋮                       ⋮          ⋮
12151 BTO:0000551             MS:1001251 NA
12152 BTO:0000763             MS:1001251 NA
12153 BTO:0000551             MS:1001251 NA
12154 BTO:0000763             MS:1001251 NA
12155 BTO:0000551             MS:1001251 NA
12156 BTO:0000763             MS:1001251 NA
12157 BTO:0000551             MS:1001251 NA
12158 BTO:0000763             MS:1001251 NA
12159 BTO:0000763             MS:1001251 NA
12160 BTO:0000763;BTO:0000551 MS:1001251 NA
12161 BTO:0000551             MS:1001251 NA
12162 BTO:0000763             MS:1001251 NA
12163 BTO:0000551             MS:1001251 NA
12164 BTO:0000763             MS:1001251 NA
12165 BTO:0000551             MS:1001251 NA
12166 BTO:0000763             MS:1001251 NA
12167 BTO:0000551             MS:1001251 NA
12168 BTO:0000763             MS:1001251 NA
12169 BTO:0000763             MS:1001251 NA
12170 BTO:0000763;BTO:0000551 MS:1001251 NA
12171 BTO:0000551             MS:1001251 NA
12172 BTO:0000763             MS:1001251 NA
12173 BTO:0000551             MS:1001251 NA
12174 BTO:0000763             MS:1001251 NA
12175 BTO:0000551             MS:1001251 NA
12176 BTO:0000763             MS:1001251 NA
12177 BTO:0000551             MS:1001251 NA
12178 BTO:0000763             MS:1001251 NA
12179 BTO:0000763             MS:1001251 NA
12180 BTO:0000763;BTO:0000551 MS:1001251 NA

## Extract tumor samples

In [7]:
channel_levels <- c(
  "126", "127N", "127C", "128N", "128C",
  "129N", "129C", "130N", "130C", "131"
)

In [8]:
phospho_ann <- unique(
  clin[
    Batch == "Phosphoproteome",
    .(
      Mixture,
      Channel,
      Subject,
      Condition,
      BioReplicate,
      Cohort
    )
  ]
)

phospho_ann[, channel_order := match(Channel, channel_levels)]
setorder(phospho_ann, Mixture, channel_order)

phospho_ann <- phospho_ann[Condition != "Norm"]
phospho_ann[, run_id := unique(phospho$run_id)]
phospho_ann[, subject_id := sub("^Patient_", "", Subject)]
phospho_ann[, subject_id := gsub("-", ".", subject_id)]

In [9]:
phospho_ann <- phospho_ann[Condition == "Lung Cancer"]
phospho <- phospho[run_id %in% phospho_ann$run_id]
uniqueN(phospho$run_id)

[1] 113

In [10]:
proteo_ann <- unique(
  clin[
    Batch == "Proteome",
    .(
      Mixture,
      Channel,
      Subject,
      Condition,
      BioReplicate,
      Cohort
    )
  ]
)

proteo_ann[, channel_order := match(Channel, channel_levels)]
setorder(proteo_ann, Mixture, channel_order)

proteo_ann <- proteo_ann[Condition != "Norm"]
proteo_ann[, run_id := unique(proteo$run_id)]
proteo_ann[, subject_id := sub("^Patient_", "", Subject)]
proteo_ann[, subject_id := gsub("-", ".", subject_id)]

In [11]:
proteo_ann <- proteo_ann[Condition == "Lung Cancer"]
proteo <- proteo[run_id %in% proteo_ann$run_id]
uniqueN(proteo$run_id)

[1] 113

In [12]:
common_subjects <- intersect(
  phospho_ann$subject_id,
  proteo_ann$subject_id
)

length(common_subjects)

[1] 111

## Exclude patients with multiple runs

In [13]:
dup_subjects_phospho <- phospho_ann[
  subject_id %in% common_subjects,
  .N,
  by = subject_id
][
  N > 1,
  subject_id
]

dup_subjects_proteo <- proteo_ann[
  subject_id %in% common_subjects,
  .N,
  by = subject_id
][
  N > 1,
  subject_id
]

dup_subjects <- union(
  dup_subjects_phospho,
  dup_subjects_proteo
)

dup_subjects

[1] "C3N.02587" "C3N.02379"

In [14]:
common_subjects <- setdiff(
  common_subjects,
  dup_subjects
)

length(common_subjects)

[1] 109

In [15]:
phospho <- phospho[
    run_id %in% phospho_ann[
        subject_id %in% common_subjects,
        run_id
        ]
    ]
phospho[, run_id := phospho_ann$subject_id[match(run_id, phospho_ann$run_id)]]
setnames(phospho, old = "run_id", new = "subject_id")
uniqueN(phospho$subject_id)

[1] 109

In [16]:
proteo <- proteo[
    run_id %in% proteo_ann[
        subject_id %in% common_subjects,
        run_id
        ]
    ]
proteo[, run_id := proteo_ann$subject_id[match(run_id, proteo_ann$run_id)]]
setnames(proteo, old = "run_id", new = "subject_id")
uniqueN(proteo$subject_id)

[1] 109

In [18]:
phospho

        gene_id protein_id peptide_id site_id
1       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
2       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
3       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
4       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
5       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
6       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
7       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
8       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
9       INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
10      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
11      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
12      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
13      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
14      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
15      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
16      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
17      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
18      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
19      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
20      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
21      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
22      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
23      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
24      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
25      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
26      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
27      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
28      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
29      INCENP  Q9NQS7     PEP_1      INCENP:Q9NQS7:S148
30      INCENP  Q9NQS7     PEP_2      INCENP:Q9NQS7:S143
⋮       ⋮       ⋮          ⋮          ⋮
1666261 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:S285
1666262 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:Y284
1666263 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:S285
1666264 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:Y284
1666265 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:S285
1666266 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:Y284
1666267 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:S285
1666268 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:Y284
1666269 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:S285
1666270 BCLAF1  Q9NYF8     PEP_52426  BCLAF1:Q9NYF8:Y284
1666271 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
1666272 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
1666273 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
1666274 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
1666275 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
1666276 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
1666277 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
1666278 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
1666279 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:S454
1666280 CLASRP  Q8N2M8     PEP_52427  CLASRP:Q8N2M8:Y453
1666281 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1666282 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1666283 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1666284 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1666285 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1666286 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1666287 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1666288 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1666289 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1666290 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
        modified_peptide_sequence    peptide_sequence             phosphosite
1       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
2       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
3       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
4       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
5       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
6       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
7       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
8       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
9       AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
10      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
11      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
12      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
13      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
14      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
15      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
16      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
17      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
18      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
19      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
20      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
21      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
22      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
23      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
24      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
25      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
26      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
27      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
28      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
29      AAAAAAAATMALAAPSSPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S148
30      AAAAAAAATMALAAPSsPTPEsPTMLTK AAAAAAAATMALAAPSSPTPESPTMLTK S143
⋮       ⋮                            ⋮                            ⋮
1666261 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              S285
1666262 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              Y284
1666263 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              S285
1666264 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              Y284
1666265 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              S285
1666266 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              Y284
1666267 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              S285
1666268 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              Y284
1666269 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              S285
1666270 ysPSQNSPIHHIPSR              YSPSQNSPIHHIPSR              Y284
1666271 ysRSPAR                      YSRSPAR                      S454
1666272 ysRSPAR                      YSRSPAR                      Y453
1666273 ysRSPAR                      YSRSPAR                      S454
1666274 ysRSPAR                      YSRSPAR                      Y453
1666275 ysRSPAR                      YSRSPAR                      S454
1666276 ysRSPAR                      YSRSPAR                      Y453
1666277 ysRSPAR                      YSRSPAR                      S454
1666278 ysRSPAR                      YSRSPAR                      Y453
1666279 ysRSPAR                      YSRSPAR                      S454
1666280 ysRSPAR                      YSRSPAR                      Y453
1666281 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
1666282 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
1666283 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
1666284 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
1666285 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
1666286 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
1666287 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
1666288 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
1666289 ysRSSSSPTEATEK               YSRSSSSPTEATEK               S1453
1666290 ysRSSSSPTEATEK               YSRSSSSPTEATEK               Y1452
        subject_id peptide_intensity
1       C3N.01799   1.153957179
2       C3L.01890   0.082273444
3       C3N.00572   0.243645247
4       C3N.02423   1.523089647
5       C3N.02729   0.370272378
6       C3L.00263   0.394220959
7       C3N.01410   0.863233993
8       C3N.00578   1.815655904
9       C3L.00893   0.010883959
10      C3N.01488   1.320739206
11      C3N.01413   0.361754632
12      C3N.01030   0.074878756
13      C3N.02588   3.340394876
14      C3N.00552  -0.433511519
15      C3L.01889   0.488164656
16      C3N.00169   1.085538974
17      C3L.00422   1.357868008
18      C3L.00083   1.280858397
19      C3N.00551  -0.416050410
20      C3N.01842  -1.853975305
21      C3N.02089   0.073408032
22      C3L.01682   0.557417956
23      C3N.01016  -0.475117463
24      C3N.00580   1.291876041
25      11LU013    -0.005850521
26      C3N.02000   0.898264993
27      C3N.01489   1.502066385
28      C3N.00737   1.563155450
29      C3N.01405   0.496228854
30      C3N.01416   0.983468140
⋮       ⋮          ⋮
1666261 C3N.00169   0.64865492
1666262 C3N.00169   0.64865492
1666263 C3L.00422   0.50849057
1666264 C3L.00422   0.50849057
1666265 C3L.00083   0.58336807
1666266 C3L.00083   0.58336807
1666267 C3N.00551   0.50379411
1666268 C3N.00551   0.50379411
1666269 C3N.01842   0.19580106
1666270 C3N.01842   0.19580106
1666271 C3L.00095   0.88399012
1666272 C3L.00095   0.88399012
1666273 C3N.02572   0.02868517
1666274 C3N.02572   0.02868517
1666275 C3N.00559   0.07878603
1666276 C3N.00559   0.07878603
1666277 C3N.00545   0.53480739
1666278 C3N.00545   0.53480739
1666279 11LU016    -0.18703769
1666280 11LU016    -0.18703769
1666281 C3N.01021   0.49851594
1666282 C3N.01021   0.49851594
1666283 C3N.00203   0.49654626
1666284 C3N.00203   0.49654626
1666285 C3L.01330   1.04963344
1666286 C3L.01330   1.04963344
1666287 C3N.00574   1.05259038
1666288 C3N.00574   1.05259038
1666289 11LU035     0.35818374
1666290 11LU035     0.35818374

In [19]:
proteo

        gene_id  protein_id peptide_id site_id
1       A1BG     P04217     P04217     A1BG:P04217:PA
2       A1CF     Q9NQ94     Q9NQ94     A1CF:Q9NQ94:PA
3       A2M      P01023     P01023     A2M:P01023:PA
4       AAAS     Q9NRG9     Q9NRG9     AAAS:Q9NRG9:PA
5       AACS     Q86V21     Q86V21     AACS:Q86V21:PA
6       AADAC    P22760     P22760     AADAC:P22760:PA
7       AADAT    Q8N5Z0     Q8N5Z0     AADAT:Q8N5Z0:PA
8       AAGAB    Q6PD74     Q6PD74     AAGAB:Q6PD74:PA
9       AAK1     Q2M2I8     Q2M2I8     AAK1:Q2M2I8:PA
10      AAMDC    Q9H7C9     Q9H7C9     AAMDC:Q9H7C9:PA
11      AAMP     Q13685     Q13685     AAMP:Q13685:PA
12      AAR2     Q9Y312     Q9Y312     AAR2:Q9Y312:PA
13      AARS     P49588     P49588     AARS:P49588:PA
14      AARS2    Q5JTZ9     Q5JTZ9     AARS2:Q5JTZ9:PA
15      AARSD1   Q9BTE6     Q9BTE6     AARSD1:Q9BTE6:PA
16      AASDHPPT Q9NRN7     Q9NRN7     AASDHPPT:Q9NRN7:PA
17      AASS     Q9UDR5     Q9UDR5     AASS:Q9UDR5:PA
18      AATF     Q9NY61     Q9NY61     AATF:Q9NY61:PA
19      AATK     Q6ZMQ8     Q6ZMQ8     AATK:Q6ZMQ8:PA
20      ABAT     P80404     P80404     ABAT:P80404:PA
21      ABCA1    O95477     O95477     ABCA1:O95477:PA
22      ABCA12   Q86UK0     Q86UK0     ABCA12:Q86UK0:PA
23      ABCA2    Q9BZC7     Q9BZC7     ABCA2:Q9BZC7:PA
24      ABCA3    Q99758     Q99758     ABCA3:Q99758:PA
25      ABCA6    Q8N139     Q8N139     ABCA6:Q8N139:PA
26      ABCA7    Q8IZY2     Q8IZY2     ABCA7:Q8IZY2:PA
27      ABCA8    O94911     O94911     ABCA8:O94911:PA
28      ABCB1    P08183     P08183     ABCB1:P08183:PA
29      ABCB10   Q9NRK6     Q9NRK6     ABCB10:Q9NRK6:PA
30      ABCB6    Q9NP58     Q9NP58     ABCB6:Q9NP58:PA
⋮       ⋮        ⋮          ⋮          ⋮
1188289 ZNF845   Q96IR2     Q96IR2     ZNF845:Q96IR2:PA
1188290 ZNF852   Q6ZMS4     Q6ZMS4     ZNF852:Q6ZMS4:PA
1188291 ZNF865   P0CJ78     P0CJ78     ZNF865:P0CJ78:PA
1188292 ZNF91    Q05481     Q05481     ZNF91:Q05481:PA
1188293 ZNFX1    Q9P2E3     Q9P2E3     ZNFX1:Q9P2E3:PA
1188294 ZNHIT1   O43257     O43257     ZNHIT1:O43257:PA
1188295 ZNHIT2   Q9UHR6     Q9UHR6     ZNHIT2:Q9UHR6:PA
1188296 ZNHIT3   Q15649     Q15649     ZNHIT3:Q15649:PA
1188297 ZNHIT6   Q9NWK9     Q9NWK9     ZNHIT6:Q9NWK9:PA
1188298 ZNRD1    Q9P1U0     Q9P1U0     ZNRD1:Q9P1U0:PA
1188299 ZNRF1    Q8ND25     Q8ND25     ZNRF1:Q8ND25:PA
1188300 ZNRF2    Q8NHG8     Q8NHG8     ZNRF2:Q8NHG8:PA
1188301 ZPR1     O75312     O75312     ZPR1:O75312:PA
1188302 ZRANB2   O95218     O95218     ZRANB2:O95218:PA
1188303 ZRSR2    Q15696     Q15696     ZRSR2:Q15696:PA
1188304 ZSCAN18  Q8TBC5     Q8TBC5     ZSCAN18:Q8TBC5:PA
1188305 ZSCAN26  Q16670     Q16670     ZSCAN26:Q16670:PA
1188306 ZSCAN31  Q96LW9     Q96LW9     ZSCAN31:Q96LW9:PA
1188307 ZSWIM4   Q9H7M6     Q9H7M6     ZSWIM4:Q9H7M6:PA
1188308 ZSWIM8   A7E2V4     A7E2V4     ZSWIM8:A7E2V4:PA
1188309 ZSWIM9   Q86XI8     Q86XI8     ZSWIM9:Q86XI8:PA
1188310 ZW10     O43264     O43264     ZW10:O43264:PA
1188311 ZWILCH   Q9H900     Q9H900     ZWILCH:Q9H900:PA
1188312 ZWINT    O95229     O95229     ZWINT:O95229:PA
1188313 ZXDA     P98168     P98168     ZXDA:P98168:PA
1188314 ZXDC     Q2QGD7     Q2QGD7     ZXDC:Q2QGD7:PA
1188315 ZYG11B   Q9C0D3     Q9C0D3     ZYG11B:Q9C0D3:PA
1188316 ZYX      Q15942     Q15942     ZYX:Q15942:PA
1188317 ZZEF1    O43149     O43149     ZZEF1:O43149:PA
1188318 ZZZ3     Q8IYH5     Q8IYH5     ZZZ3:Q8IYH5:PA
        modified_peptide_sequence peptide_sequence phosphosite subject_id
1       P04217                    P04217           PA          C3N.01799
2       Q9NQ94                    Q9NQ94           PA          C3N.01799
3       P01023                    P01023           PA          C3N.01799
4       Q9NRG9                    Q9NRG9           PA          C3N.01799
5       Q86V21                    Q86V21           PA          C3N.01799
6       P22760                    P22760           PA          C3N.01799
7       Q8N5Z0                    Q8N5Z0           PA          C3N.01799
8       Q6PD74                    Q6PD74           PA          C3N.01799
9       Q2M2I8                    Q2M2I8           PA          C3N.01799
10      Q9H7C9                    Q9H7C9           PA          C3N.01799
11      Q13685                    Q13685           PA          C3N.01799
12      Q9Y312                    Q9Y312           PA          C3N.01799
13      P49588                    P49588           PA          C3N.01799
14      Q5JTZ9                    Q5JTZ9           PA          C3N.01799
15      Q9BTE6                    Q9BTE6           PA          C3N.01799
16      Q9NRN7                    Q9NRN7           PA          C3N.01799
17      Q9UDR5                    Q9UDR5           PA          C3N.01799
18      Q9NY61                    Q9NY61           PA          C3N.01799
19      Q6ZMQ8                    Q6ZMQ8           PA          C3N.01799
20      P80404                    P80404           PA          C3N.01799
21      O95477                    O95477           PA          C3N.01799
22      Q86UK0                    Q86UK0           PA          C3N.01799
23      Q9BZC7                    Q9BZC7           PA          C3N.01799
24      Q99758                    Q99758           PA          C3N.01799
25      Q8N139                    Q8N139           PA          C3N.01799
26      Q8IZY2                    Q8IZY2           PA          C3N.01799
27      O94911                    O94911           PA          C3N.01799
28      P08183                    P08183           PA          C3N.01799
29      Q9NRK6                    Q9NRK6           PA          C3N.01799
30      Q9NP58                    Q9NP58           PA          C3N.01799
⋮       ⋮                         ⋮                ⋮           ⋮
1188289 Q96IR2                    Q96IR2           PA          C3L.02365
1188290 Q6ZMS4                    Q6ZMS4           PA          C3L.02365
1188291 P0CJ78                    P0CJ78           PA          C3L.02365
1188292 Q05481                    Q05481           PA          C3L.02365
1188293 Q9P2E3                    Q9P2E3           PA          C3L.02365
1188294 O43257                    O43257           PA          C3L.02365
1188295 Q9UHR6                    Q9UHR6           PA          C3L.02365
1188296 Q15649                    Q15649           PA          C3L.02365
1188297 Q9NWK9                    Q9NWK9           PA          C3L.02365
1188298 Q9P1U0                    Q9P1U0           PA          C3L.02365
1188299 Q8ND25                    Q8ND25           PA          C3L.02365
1188300 Q8NHG8                    Q8NHG8           PA          C3L.02365
1188301 O75312                    O75312           PA          C3L.02365
1188302 O95218                    O95218           PA          C3L.02365
1188303 Q15696                    Q15696           PA          C3L.02365
1188304 Q8TBC5                    Q8TBC5           PA          C3L.02365
1188305 Q16670                    Q16670           PA          C3L.02365
1188306 Q96LW9                    Q96LW9           PA          C3L.02365
1188307 Q9H7M6                    Q9H7M6           PA          C3L.02365
1188308 A7E2V4                    A7E2V4           PA          C3L.02365
1188309 Q86XI8                    Q86XI8           PA          C3L.02365
1188310 O43264                    O43264           PA          C3L.02365
1188311 Q9H900                    Q9H900           PA          C3L.02365
1188312 O95229                    O95229           PA          C3L.02365
1188313 P98168                    P98168           PA          C3L.02365
1188314 Q2QGD7                    Q2QGD7           PA          C3L.02365
1188315 Q9C0D3                    Q9C0D3           PA          C3L.02365
1188316 Q15942                    Q15942           PA          C3L.02365
1188317 O43149                    O43149           PA          C3L.02365
1188318 Q8IYH5                    Q8IYH5           PA          C3L.02365
        peptide_intensity
1       -0.608178218
2                 NA
3       -0.852777619
4        0.063600148
5       -0.124289958
6       -2.281265494
7       -0.869112802
8       -0.091862293
9       -0.002046645
10       0.175400585
11       0.339276762
12       0.021640839
13       0.255146168
14      -0.150221550
15       0.358136801
16       0.386885484
17       0.209195785
18       0.775807351
19      -0.438669789
20       0.500467253
21      -0.444890962
22                NA
23       0.467599205
24      -1.556549386
25      -0.233133122
26       0.095722294
27      -0.698130760
28      -0.182074489
29       0.843830594
30       0.098256078
⋮       ⋮
1188289  0.084880782
1188290  0.008463618
1188291  0.028505133
1188292 -1.272243187
1188293  0.039186056
1188294  0.022103844
1188295  0.389311570
1188296  0.786069373
1188297  0.331206974
1188298  0.469521379
1188299           NA
1188300  0.760047377
1188301  0.263422738
1188302 -0.159960258
1188303  0.046598250
1188304 -0.084976433
1188305 -0.436408507
1188306  0.616883694
1188307           NA
1188308  0.059523678
1188309 -0.259824881
1188310  0.188072418
1188311  0.576057857
1188312           NA
1188313           NA
1188314  0.161522957
1188315  0.198434577
1188316 -0.091167078
1188317  0.127596703
1188318  0.022041477

In [20]:
dir.create("./data/cptac-luad/processed")

Warning message in dir.create("./data/cptac-luad/processed"):
“'./data/cptac-luad/processed' already exists”

In [21]:
saveRDS(phospho, "./data/cptac-luad/processed/CPTAC_LUAD_phospho.rds")
saveRDS(proteo,  "./data/cptac-luad/processed/CPTAC_LUAD_proteo.rds")