# 00-3. Preprocessing (U54-DP)

In [26]:
library(data.table)
library(plyr)
library(vespa)
library(viper)
library(reshape2)

Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt

In [4]:
if (!dir.exists("./data/u54-dp")) {
  out <- system2(
    "bash",
    "./tools/scripts/u54-dp.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

  % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
                                 Dload  Upload  Total   Spent   Left   Speed
100 53.37M 100 53.37M   0      0 130.0M      0                              0
Archive:  ./data.zip
  inflating: ./U54_COAD_phospho.rds
  inflating: ./U54BL_COAD_phospho.rds
  inflating: ./U54BL_COAD_proteo.rds
  inflating: ./U54DP_COAD_phospho.rds

In [3]:
if (!file.exists("./tools/references/library.fasta")) {
  out <- system2(
    "bash",
    "./tools/scripts/fasta.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

In [12]:
dt <- readRDS("./data/u54-dp/U54DP_COAD_phospho.rds")
dt <- as.data.table(dt)
dt[, run_id := as.character(run_id)]

In [15]:
meta <- unique(dt[, .(run_id)])
meta[, c("cell_code", "drug_code", "time_point") := tstrsplit(run_id, "_", fixed = TRUE)]
meta

    run_id       cell_code drug_code time_point
1   H508_AL_96h  H508      AL        96h
2   H508_AL_24h  H508      AL        24h
3   H508_LI_96h  H508      LI        96h
4   SNU_OS_24h   SNU       OS        24h
5   H508_WI_1h   H508      WI        1h
6   M8_WI_96h    M8        WI        96h
7   SNU_WI_96h   SNU       WI        96h
8   LS_RA_24h    LS        RA        24h
9   LS_C_24h     LS        C         24h
10  HCT_RA_1h    HCT       RA        1h
11  SNU_TR_1h    SNU       TR        1h
12  HCT_AL_1h    HCT       AL        1h
13  SNU_C_1h     SNU       C         1h
14  LS_AL_96h    LS        AL        96h
15  SNU_RA_1h    SNU       RA        1h
16  LS_LI_96h    LS        LI        96h
17  LS_WI_96h    LS        WI        96h
18  HT115_TR_24h HT115     TR        24h
19  LS_IM_1h     LS        IM        1h
20  SNU_OS_96h   SNU       OS        96h
21  LS_TR_1h     LS        TR        1h
22  M8_WI_24h    M8        WI        24h
23  HCT_TR_1h    HCT       TR        1h
24  SNU_IM_24h   SNU       IM        24h
25  LS_OS_96h    LS        OS        96h
26  SNU_AL_96h   SNU       AL        96h
27  HT115_C_24h  HT115     C         24h
28  SNU_WI_24h   SNU       WI        24h
29  HCT_IM_24h   HCT       IM        24h
30  HT115_WI_24h HT115     WI        24h
⋮   ⋮            ⋮         ⋮         ⋮
115 HCT_IM_96h   HCT       IM        96h
116 HT115_C_96h  HT115     C         96h
117 SNU_TR_24h   SNU       TR        24h
118 H508_C_96h   H508      C         96h
119 H508_IM_1h   H508      IM        1h
120 HT115_C_1h   HT115     C         1h
121 H508_LI_1h   H508      LI        1h
122 M8_AL_1h     M8        AL        1h
123 M8_C_24h     M8        C         24h
124 M8_TR_96h    M8        TR        96h
125 M8_IM_96h    M8        IM        96h
126 M8_TR_1h     M8        TR        1h
127 M8_C_1h      M8        C         1h
128 HT115_TR_96h HT115     TR        96h
129 M8_LI_24h    M8        LI        24h
130 M8_OS_1h     M8        OS        1h
131 M8_IM_24h    M8        IM        24h
132 M8_AL_24h    M8        AL        24h
133 M8_OS_96h    M8        OS        96h
134 M8_OS_24h    M8        OS        24h
135 M8_RA_24h    M8        RA        24h
136 HT115_TR_1h  HT115     TR        1h
137 M8_TR_24h    M8        TR        24h
138 M8_RA_1h     M8        RA        1h
139 M8_RA_96h    M8        RA        96h
140 M8_WI_1h     M8        WI        1h
141 M8_LI_1h     M8        LI        1h
142 M8_LI_96h    M8        LI        96h
143 M8_IM_1h     M8        IM        1h
144 LS_AL_1h     LS        AL        1h

In [16]:
meta[, cell_line := fifelse(cell_code == "H508", "NCI-H508",
                     fifelse(cell_code == "LS",   "LS1034",
                     fifelse(cell_code == "M8",   "MDST8",
                     fifelse(cell_code == "SNU",  "SNU-61",
                     fifelse(cell_code == "H15",  "HCT-15",
                     fifelse(cell_code == "HT",   "HT115", cell_code))))))]

meta[, drug := fifelse(drug_code == "AL", "alpelisib",
                fifelse(drug_code == "IM", "imatinib",
                fifelse(drug_code == "LI", "linsitinib",
                fifelse(drug_code == "OS", "osimertinib",
                fifelse(drug_code == "RA", "ralimetinib",
                fifelse(drug_code == "TR", "trametinib",
                fifelse(drug_code == "WI", "WIKI4",
                fifelse(drug_code == "C",  "DMSO", drug_code))))))))]

In [17]:
dt <- merge(dt, meta, by = "run_id", all.x = TRUE)

In [20]:
get_vpmx<-function(osw, spregulon, aregulon, library) {
  # VESPA (substrate-protein)
  spvpl<-viperize(osw, spregulon, xc=TRUE, normalize=TRUE)
  spvpmx<-reshape2::dcast(spvpl,protein_id~tag,value.var="nes",fill=0)
  spvpmx_proteins<-spvpmx$protein_id
  spvpmx$protein_id<-NULL
  spvpmx<-as.matrix(spvpmx)
  row.names(spvpmx)<-spvpmx_proteins
  
  # VESPA (substrate-protein)
  spvpl2<-viperize(osw, spregulon, xc=TRUE, normalize=FALSE)
  spvpmx2<-reshape2::dcast(spvpl2,protein_id~tag,value.var="nes",fill=0)
  spvpmx2_proteins<-spvpmx2$protein_id
  spvpmx2$protein_id<-NULL
  spvpmx2<-as.matrix(spvpmx2)
  row.names(spvpmx2)<-spvpmx2_proteins
  
  # VESPA (activity-protein)
  apvpl<-viperize(vmx2pv(spvpmx2, fasta=library), aregulon, xc=TRUE, normalize=TRUE)
  apvpmx<-reshape2::dcast(apvpl,protein_id~tag,value.var="nes",fill=0)
  apvpmx_proteins<-apvpmx$protein_id
  apvpmx$protein_id<-NULL
  apvpmx<-as.matrix(apvpmx)
  row.names(apvpmx)<-apvpmx_proteins
  
  # integrate substrate and activity-levels
  ipvpl<-ddply(rbind(melt(spvpmx),melt(apvpmx)),.(Var1,Var2),function(X){data.frame("value"=sum(X$value)/sqrt(length(X$value)))})
  ipvpmx<-dcast(ipvpl, Var1~Var2, value.var="value")
  ipvpmx_proteins<-ipvpmx$Var1
  ipvpmx<-as.matrix(ipvpmx[,-1])
  rownames(ipvpmx)<-ipvpmx_proteins
  
  ipvpmx<-ipvpmx[,colnames(apvpmx)]
  
  return(list("substrate"=spvpmx, "activity"=apvpmx, "integrated"=ipvpmx))
}

In [21]:
viperize<-function(osw, regulon, min_size = 10, topn = 500, xc = TRUE, normalize = TRUE){
  # generate quantitative matrix
  qmn<-export2mx(osw, fillvalues = "colmin")
  
  if (normalize) {
    # rank based normalization of the matrix
    qmn.d1 <- t(t(apply(qmn, 2, rank, na.last = "keep"))/(colSums(!is.na(qmn)) + 1))
    
    # rank based estimation of single sample gene expression signature across the matrix
    qmn.norm <- t(apply(qmn.d1, 1, rank, na.last = "keep"))/(rowSums(!is.na(qmn.d1)) + 1)
  } else {
    qmn.norm <- qmn
  }
  
  # run VIPER
  vpres<-viper(qmn.norm, vespa::pruneRegulon(vespa::subsetRegulon(regulon, rownames(qmn.norm), min_size=min_size), cutoff=topn), minsize=min_size, pleiotropy = xc, pleiotropyArgs = list(regulators = 0.05, shadow = 0.05, targets = 5, penalty = 20, method = "adaptive"), cores=6)
  
  # transform viper results
  vpd<-as.data.frame(vpres)
  vpd$protein_id<-row.names(vpd)
  vpl<-reshape2::melt(vpd, id=c("protein_id"), variable.name = "tag", value.name = "nes")

  return(vpl)
}

In [23]:
library <- "./tools/references/library.fasta"
spregulon <- readRDS("./runs/cptac-coad/vespa.net/results/stdpimeta_substrate_protein_regulon.rds")
aregulon <- readRDS("./runs/cptac-coad/vespa.net/results/dpimeta_activity_protein_regulon.rds")

In [39]:
new_sites <- unique(dt$site_id)
new_sites <- new_sites[!is.na(new_sites)]

sp_targets <- unique(unlist(lapply(spregulon, function(x) {
  names(x$tfmode)
})))

sp_targets <- sp_targets[!is.na(sp_targets)]

sp_overlap <- intersect(new_sites, sp_targets)

length(sp_overlap)
length(new_sites)
length(sp_targets)

overlap_new_vs_sp <- length(sp_overlap) / length(new_sites)
overlap_sp_vs_new <- length(sp_overlap) / length(sp_targets)

overlap_new_vs_sp
overlap_sp_vs_new

[1] 6200

[1] 13529

[1] 16578

[1] 0.4582748

[1] 0.3739896

In [40]:
dvespa_input <- readRDS("./data/cptac-coad/processed/CPTAC_COAD_phospho.rds")
dvespa_input

        gene_id   protein_id peptide_id
1       UBA6      A0AVT1     UBA6_S36__A0AVT1:S36
2       ESYT2     A0FGR8     ESYT2_S693__A0FGR8:S693
3       ESYT2     A0FGR8     ESYT2_S704__A0FGR8:S704
4       ESYT2     A0FGR8     ESYT2_S739__A0FGR8:S739
5       ESYT2     A0FGR8     ESYT2_S755__A0FGR8:S755
6       ESYT2     A0FGR8     ESYT2_S758__A0FGR8:S758
7       ESYT2     A0FGR8     ESYT2_S761__A0FGR8:S761
8       ESYT2     A0FGR8     ESYT2_T705__A0FGR8:T705
9       MED19     A0JLT2     MED19_S226__A0JLT2:S226
10      UHRF1BP1L A0JNW5     UHRF1BP1L_S1402__A0JNW5:S1402
11      UHRF1BP1L A0JNW5     UHRF1BP1L_S891__A0JNW5:S891
12      UHRF1BP1L A0JNW5     UHRF1BP1L_S939__A0JNW5:S939
13      UHRF1BP1L A0JNW5     UHRF1BP1L_S989__A0JNW5:S989
14      SHTN1     A0MZ66     SHTN1_S494__A0MZ66:S494
15      BICDL2    A1A5D9     BICDL2_S277__A1A5D9:S277
16      BICDL2    A1A5D9     BICDL2_S36__A1A5D9:S36
17      BICDL2    A1A5D9     BICDL2_T348__A1A5D9:T348
18      C1orf226  A1L170     C1orf226_S198__A1L170:S198
19      C1orf226  A1L170     C1orf226_S222__A1L170:S222
20      C1orf226  A1L170     C1orf226_S244__A1L170:S244
21      PLEKHG3   A1L390     PLEKHG3_S1037__A1L390:S1037
22      PLEKHG3   A1L390     PLEKHG3_S1040__A1L390:S1040
23      PLEKHG3   A1L390     PLEKHG3_S1081__A1L390:S1081
24      PLEKHG3   A1L390     PLEKHG3_S1154__A1L390:S1154
25      PLEKHG3   A1L390     PLEKHG3_S1169__A1L390:S1169
26      PLEKHG3   A1L390     PLEKHG3_S433__A1L390:S433
27      PLEKHG3   A1L390     PLEKHG3_S488__A1L390:S488
28      PLEKHG3   A1L390     PLEKHG3_S576__A1L390:S576
29      PLEKHG3   A1L390     PLEKHG3_S577__A1L390:S577
30      PLEKHG3   A1L390     PLEKHG3_S618__A1L390:S618
⋮       ⋮         ⋮          ⋮
1224079 SLC4A4    Q9Y6R1     SLC4A4_S262__Q9Y6R1:S262
1224080 SLC4A4    Q9Y6R1     SLC4A4_S65__Q9Y6R1:S65
1224081 SLC4A4    Q9Y6R1     SLC4A4_S68__Q9Y6R1:S68
1224082 SLC4A4    Q9Y6R1     SLC4A4_S79__Q9Y6R1:S79
1224083 MAP3K4    Q9Y6R4     MAP3K4_S1252__Q9Y6R4:S1252
1224084 MAP3K4    Q9Y6R4     MAP3K4_S431__Q9Y6R4:S431
1224085 MAP3K4    Q9Y6R4     MAP3K4_S499__Q9Y6R4:S499
1224086 MAP3K4    Q9Y6R4     MAP3K4_S66__Q9Y6R4:S66
1224087 MAP3K4    Q9Y6R4     MAP3K4_T83__Q9Y6R4:T83
1224088 CCDC61    Q9Y6R9     CCDC61_S334__Q9Y6R9:S334
1224089 CCDC61    Q9Y6R9     CCDC61_S336__Q9Y6R9:S336
1224090 CCDC61    Q9Y6R9     CCDC61_S373__Q9Y6R9:S373
1224091 CCDC61    Q9Y6R9     CCDC61_S376__Q9Y6R9:S376
1224092 PCLO      Q9Y6V0     PCLO_S772__Q9Y6V0:S772
1224093 WASF2     Q9Y6W5     WASF2_T129__Q9Y6W5:T129
1224094 FAM169A   Q9Y6X4     FAM169A_S376__Q9Y6X4:S376
1224095 FAM169A   Q9Y6X4     FAM169A_S378__Q9Y6X4:S378
1224096 FAM169A   Q9Y6X4     FAM169A_S449__Q9Y6X4:S449
1224097 FAM169A   Q9Y6X4     FAM169A_S526__Q9Y6X4:S526
1224098 ZHX2      Q9Y6X8     ZHX2_T37__Q9Y6X8:T37
1224099 MORC2     Q9Y6X9     MORC2_S615__Q9Y6X9:S615
1224100 MORC2     Q9Y6X9     MORC2_S725__Q9Y6X9:S725
1224101 MORC2     Q9Y6X9     MORC2_S739__Q9Y6X9:S739
1224102 MORC2     Q9Y6X9     MORC2_S743__Q9Y6X9:S743
1224103 MORC2     Q9Y6X9     MORC2_S777__Q9Y6X9:S777
1224104 MORC2     Q9Y6X9     MORC2_S779__Q9Y6X9:S779
1224105 IVNS1ABP  Q9Y6Y0     IVNS1ABP_S277__Q9Y6Y0:S277
1224106 IVNS1ABP  Q9Y6Y0     IVNS1ABP_S322__Q9Y6Y0:S322
1224107 IVNS1ABP  Q9Y6Y0     IVNS1ABP_S326__Q9Y6Y0:S326
1224108 IVNS1ABP  Q9Y6Y0     IVNS1ABP_S338__Q9Y6Y0:S338
        site_id                modified_peptide_sequence
1       UBA6:A0AVT1:S36        UBA6_S36__A0AVT1:S36
2       ESYT2:A0FGR8:S693      ESYT2_S693__A0FGR8:S693
3       ESYT2:A0FGR8:S704      ESYT2_S704__A0FGR8:S704
4       ESYT2:A0FGR8:S739      ESYT2_S739__A0FGR8:S739
5       ESYT2:A0FGR8:S755      ESYT2_S755__A0FGR8:S755
6       ESYT2:A0FGR8:S758      ESYT2_S758__A0FGR8:S758
7       ESYT2:A0FGR8:S761      ESYT2_S761__A0FGR8:S761
8       ESYT2:A0FGR8:T705      ESYT2_T705__A0FGR8:T705
9       MED19:A0JLT2:S226      MED19_S226__A0JLT2:S226
10      UHRF1BP1L:A0JNW5:S1402 UHRF1BP1L_S1402__A0JNW5:S1402
11      UHRF1BP1L:A0JNW5:S891  UHRF1BP1L_S891__A0JNW5:S891
12      UHRF1BP1L:A0JNW5:S939  UHRF1BP1L_S939__A0JNW5:S939
13      UHRF1BP1L:A0JNW5:S989  UHRF1BP1L_S989__A0JNW5:S989
14      SHTN1:A0MZ66:S494      SHTN1_S494__A0MZ66:S494
15      BICDL2:A1A5D9:S277     BICDL2_S277__A1A5D9:S277
16      BICDL2:A1A5D9:S36      BICDL2_S36__A1A5D9:S36
17      BICDL2:A1A5D9:T348     BICDL2_T348__A1A5D9:T348
18      C1orf226:A1L170:S198   C1orf226_S198__A1L170:S198
19      C1orf226:A1L170:S222   C1orf226_S222__A1L170:S222
20      C1orf226:A1L170:S244   C1orf226_S244__A1L170:S244
21      PLEKHG3:A1L390:S1037   PLEKHG3_S1037__A1L390:S1037
22      PLEKHG3:A1L390:S1040   PLEKHG3_S1040__A1L390:S1040
23      PLEKHG3:A1L390:S1081   PLEKHG3_S1081__A1L390:S1081
24      PLEKHG3:A1L390:S1154   PLEKHG3_S1154__A1L390:S1154
25      PLEKHG3:A1L390:S1169   PLEKHG3_S1169__A1L390:S1169
26      PLEKHG3:A1L390:S433    PLEKHG3_S433__A1L390:S433
27      PLEKHG3:A1L390:S488    PLEKHG3_S488__A1L390:S488
28      PLEKHG3:A1L390:S576    PLEKHG3_S576__A1L390:S576
29      PLEKHG3:A1L390:S577    PLEKHG3_S577__A1L390:S577
30      PLEKHG3:A1L390:S618    PLEKHG3_S618__A1L390:S618
⋮       ⋮                      ⋮
1224079 SLC4A4:Q9Y6R1:S262     SLC4A4_S262__Q9Y6R1:S262
1224080 SLC4A4:Q9Y6R1:S65      SLC4A4_S65__Q9Y6R1:S65
1224081 SLC4A4:Q9Y6R1:S68      SLC4A4_S68__Q9Y6R1:S68
1224082 SLC4A4:Q9Y6R1:S79      SLC4A4_S79__Q9Y6R1:S79
1224083 MAP3K4:Q9Y6R4:S1252    MAP3K4_S1252__Q9Y6R4:S1252
1224084 MAP3K4:Q9Y6R4:S431     MAP3K4_S431__Q9Y6R4:S431
1224085 MAP3K4:Q9Y6R4:S499     MAP3K4_S499__Q9Y6R4:S499
1224086 MAP3K4:Q9Y6R4:S66      MAP3K4_S66__Q9Y6R4:S66
1224087 MAP3K4:Q9Y6R4:T83      MAP3K4_T83__Q9Y6R4:T83
1224088 CCDC61:Q9Y6R9:S334     CCDC61_S334__Q9Y6R9:S334
1224089 CCDC61:Q9Y6R9:S336     CCDC61_S336__Q9Y6R9:S336
1224090 CCDC61:Q9Y6R9:S373     CCDC61_S373__Q9Y6R9:S373
1224091 CCDC61:Q9Y6R9:S376     CCDC61_S376__Q9Y6R9:S376
1224092 PCLO:Q9Y6V0:S772       PCLO_S772__Q9Y6V0:S772
1224093 WASF2:Q9Y6W5:T129      WASF2_T129__Q9Y6W5:T129
1224094 FAM169A:Q9Y6X4:S376    FAM169A_S376__Q9Y6X4:S376
1224095 FAM169A:Q9Y6X4:S378    FAM169A_S378__Q9Y6X4:S378
1224096 FAM169A:Q9Y6X4:S449    FAM169A_S449__Q9Y6X4:S449
1224097 FAM169A:Q9Y6X4:S526    FAM169A_S526__Q9Y6X4:S526
1224098 ZHX2:Q9Y6X8:T37        ZHX2_T37__Q9Y6X8:T37
1224099 MORC2:Q9Y6X9:S615      MORC2_S615__Q9Y6X9:S615
1224100 MORC2:Q9Y6X9:S725      MORC2_S725__Q9Y6X9:S725
1224101 MORC2:Q9Y6X9:S739      MORC2_S739__Q9Y6X9:S739
1224102 MORC2:Q9Y6X9:S743      MORC2_S743__Q9Y6X9:S743
1224103 MORC2:Q9Y6X9:S777      MORC2_S777__Q9Y6X9:S777
1224104 MORC2:Q9Y6X9:S779      MORC2_S779__Q9Y6X9:S779
1224105 IVNS1ABP:Q9Y6Y0:S277   IVNS1ABP_S277__Q9Y6Y0:S277
1224106 IVNS1ABP:Q9Y6Y0:S322   IVNS1ABP_S322__Q9Y6Y0:S322
1224107 IVNS1ABP:Q9Y6Y0:S326   IVNS1ABP_S326__Q9Y6Y0:S326
1224108 IVNS1ABP:Q9Y6Y0:S338   IVNS1ABP_S338__Q9Y6Y0:S338
        peptide_sequence              phosphosite run_id  peptide_intensity
1       UBA6_S36__A0AVT1:S36          S36         01CO005 -0.6170
2       ESYT2_S693__A0FGR8:S693       S693        01CO005 -0.9340
3       ESYT2_S704__A0FGR8:S704       S704        01CO005 -0.4740
4       ESYT2_S739__A0FGR8:S739       S739        01CO005 -1.3800
5       ESYT2_S755__A0FGR8:S755       S755        01CO005 -0.9565
6       ESYT2_S758__A0FGR8:S758       S758        01CO005 -0.9565
7       ESYT2_S761__A0FGR8:S761       S761        01CO005 -0.7120
8       ESYT2_T705__A0FGR8:T705       T705        01CO005 -0.4740
9       MED19_S226__A0JLT2:S226       S226        01CO005  0.1150
10      UHRF1BP1L_S1402__A0JNW5:S1402 S1402       01CO005 -0.9340
11      UHRF1BP1L_S891__A0JNW5:S891   S891        01CO005 -0.8680
12      UHRF1BP1L_S939__A0JNW5:S939   S939        01CO005 -1.4100
13      UHRF1BP1L_S989__A0JNW5:S989   S989        01CO005 -0.5020
14      SHTN1_S494__A0MZ66:S494       S494        01CO005 -0.3610
15      BICDL2_S277__A1A5D9:S277      S277        01CO005 -0.4480
16      BICDL2_S36__A1A5D9:S36        S36         01CO005 -1.4800
17      BICDL2_T348__A1A5D9:T348      T348        01CO005 -1.5230
18      C1orf226_S198__A1L170:S198    S198        01CO005 -0.3980
19      C1orf226_S222__A1L170:S222    S222        01CO005 -0.3640
20      C1orf226_S244__A1L170:S244    S244        01CO005 -1.1170
21      PLEKHG3_S1037__A1L390:S1037   S1037       01CO005 -0.5240
22      PLEKHG3_S1040__A1L390:S1040   S1040       01CO005 -0.1780
23      PLEKHG3_S1081__A1L390:S1081   S1081       01CO005 -0.7300
24      PLEKHG3_S1154__A1L390:S1154   S1154       01CO005 -0.2625
25      PLEKHG3_S1169__A1L390:S1169   S1169       01CO005 -0.4225
26      PLEKHG3_S433__A1L390:S433     S433        01CO005 -1.0040
27      PLEKHG3_S488__A1L390:S488     S488        01CO005  0.1780
28      PLEKHG3_S576__A1L390:S576     S576        01CO005 -0.1660
29      PLEKHG3_S577__A1L390:S577     S577        01CO005 -0.1660
30      PLEKHG3_S618__A1L390:S618     S618        01CO005 -1.3660
⋮       ⋮                             ⋮           ⋮       ⋮
1224079 SLC4A4_S262__Q9Y6R1:S262      S262        27CO004 -0.9320
1224080 SLC4A4_S65__Q9Y6R1:S65        S65         27CO004 -1.0260
1224081 SLC4A4_S68__Q9Y6R1:S68        S68         27CO004 -1.3690
1224082 SLC4A4_S79__Q9Y6R1:S79        S79         27CO004 -0.6830
1224083 MAP3K4_S1252__Q9Y6R4:S1252    S1252       27CO004  0.7250
1224084 MAP3K4_S431__Q9Y6R4:S431      S431        27CO004 -0.1390
1224085 MAP3K4_S499__Q9Y6R4:S499      S499        27CO004  0.6170
1224086 MAP3K4_S66__Q9Y6R4:S66        S66         27CO004  0.0050
1224087 MAP3K4_T83__Q9Y6R4:T83        T83         27CO004  0.0050
1224088 CCDC61_S334__Q9Y6R9:S334      S334        27CO004 -0.8325
1224089 CCDC61_S336__Q9Y6R9:S336      S336        27CO004 -1.0920
1224090 CCDC61_S373__Q9Y6R9:S373      S373        27CO004 -0.0710
1224091 CCDC61_S376__Q9Y6R9:S376      S376        27CO004 -0.1910
1224092 PCLO_S772__Q9Y6V0:S772        S772        27CO004  0.7160
1224093 WASF2_T129__Q9Y6W5:T129       T129        27CO004  0.2450
1224094 FAM169A_S376__Q9Y6X4:S376     S376        27CO004  0.1550
1224095 FAM169A_S378__Q9Y6X4:S378     S378        27CO004  0.1550
1224096 FAM169A_S449__Q9Y6X4:S449     S449        27CO004  0.1790
1224097 FAM169A_S526__Q9Y6X4:S526     S526        27CO004 -0.1130
1224098 ZHX2_T37__Q9Y6X8:T37          T37         27CO004 -0.4050
1224099 MORC2_S615__Q9Y6X9:S615       S615        27CO004 -0.6180
1224100 MORC2_S725__Q9Y6X9:S725       S725        27CO004  0.4370
1224101 MORC2_S739__Q9Y6X9:S739       S739        27CO004  0.2870
1224102 MORC2_S743__Q9Y6X9:S743       S743        27CO004  0.2870
1224103 MORC2_S777__Q9Y6X9:S777       S777        27CO004 -0.1460
1224104 MORC2_S779__Q9Y6X9:S779       S779        27CO004 -0.1585
1224105 IVNS1ABP_S277__Q9Y6Y0:S277    S277        27CO004  0.0330
1224106 IVNS1ABP_S322__Q9Y6Y0:S322    S322        27CO004 -0.9605
1224107 IVNS1ABP_S326__Q9Y6Y0:S326    S326        27CO004 -0.0540
1224108 IVNS1ABP_S338__Q9Y6Y0:S338    S338        27CO004  0.1090

In [41]:
dvespa_sites <- unique(dvespa_input$site_id)
dvespa_sites <- dvespa_sites[!is.na(dvespa_sites)]

ov <- intersect(new_sites, dvespa_sites)

data.frame(
  n_new_sites = length(new_sites),
  n_dvespa_sites = length(dvespa_sites),
  n_overlap = length(ov),
  frac_new_sites_in_dvespa = length(ov) / length(new_sites),
  frac_dvespa_sites_in_new = length(ov) / length(dvespa_sites)
)

  n_new_sites n_dvespa_sites n_overlap frac_new_sites_in_dvespa
1 13529       31339          8309      0.6141622
  frac_dvespa_sites_in_new
1 0.2651329

In [42]:
dt

        run_id     gene_id protein_id
1       H508_AL_1h EIF3J   O75822
2       H508_AL_1h EIF3J   O75822
3       H508_AL_1h EIF3J   O75822
4       H508_AL_1h VPS51   Q9UID3
5       H508_AL_1h VPS51   Q9UID3
6       H508_AL_1h VPS51   Q9UID3
7       H508_AL_1h POLE4   Q9NR33
8       H508_AL_1h POLE4   Q9NR33
9       H508_AL_1h FOXK2   Q01167
10      H508_AL_1h FOXK2   Q01167
11      H508_AL_1h FOXK2   Q01167
12      H508_AL_1h PRPF4B  Q13523
13      H508_AL_1h PRPF4B  Q13523
14      H508_AL_1h TOMM22  Q9NS69
15      H508_AL_1h TOMM22  Q9NS69
16      H508_AL_1h RAVER1  Q8IY67
17      H508_AL_1h RAVER1  Q8IY67
18      H508_AL_1h ADSL    P30566
19      H508_AL_1h NPM3    O75607
20      H508_AL_1h NPM3    O75607
21      H508_AL_1h ZNF316  A6NFI3
22      H508_AL_1h ZNF316  A6NFI3
23      H508_AL_1h DDX47   Q9H0S4
24      H508_AL_1h DDX47   Q9H0S4
25      H508_AL_1h KAT8    Q9H7Z6
26      H508_AL_1h KAT8    Q9H7Z6
27      H508_AL_1h KAT8    Q9H7Z6
28      H508_AL_1h KAT8    Q9H7Z6
29      H508_AL_1h KAT8    Q9H7Z6
30      H508_AL_1h KAT8    Q9H7Z6
⋮       ⋮          ⋮       ⋮
1397448 SNU_WI_96h MYO18A  Q92614
1397449 SNU_WI_96h MYO18A  Q92614
1397450 SNU_WI_96h MYO18A  Q92614
1397451 SNU_WI_96h MYO18A  Q92614
1397452 SNU_WI_96h MYO18A  Q92614
1397453 SNU_WI_96h MYO18A  Q92614
1397454 SNU_WI_96h ACAP2   Q15057
1397455 SNU_WI_96h MLLT6   P55198
1397456 SNU_WI_96h BCLAF1  Q9NYF8
1397457 SNU_WI_96h BCLAF1  Q9NYF8
1397458 SNU_WI_96h POLR2A  P24928
1397459 SNU_WI_96h POLR2A  P24928
1397460 SNU_WI_96h POLR2A  P24928
1397461 SNU_WI_96h POLR2A  P24928
1397462 SNU_WI_96h POLR2A  P24928
1397463 SNU_WI_96h POLR2A  P24928
1397464 SNU_WI_96h OCLN    Q16625
1397465 SNU_WI_96h OCLN    Q16625
1397466 SNU_WI_96h RECQL5  O94762
1397467 SNU_WI_96h RPLP2   P05387
1397468 SNU_WI_96h RPLP2   P05387
1397469 SNU_WI_96h RPLP2   P05387
1397470 SNU_WI_96h KRI1    Q8N9T8
1397471 SNU_WI_96h KRI1    Q8N9T8
1397472 SNU_WI_96h ARFGAP1 Q8N6T3
1397473 SNU_WI_96h PARG    Q86W56
1397474 SNU_WI_96h EPS8L2  Q9H6S3
1397475 SNU_WI_96h EPS8L2  Q9H6S3
1397476 SNU_WI_96h HNRNPL  P14866
1397477 SNU_WI_96h NCOA7   Q8NI08
        peptide_id
1       .(Acetyl)AAAAAAAGDS(Phospho)DS(Phospho)WDADAFSVEDPVRK_1
2       .(Acetyl)AAAAAAAGDS(Phospho)DS(Phospho)WDADAFSVEDPVRK_1
3       .(Acetyl)AAAAAAAGDSDS(Phospho)WDADAFSVEDPVR_33518
4       .(Acetyl)AAAAAAGPS(Phospho)PGSGPGDS(Phospho)PEGPEGEAPER_1113
5       .(Acetyl)AAAAAAGPS(Phospho)PGSGPGDS(Phospho)PEGPEGEAPER_1113
6       .(Acetyl)AAAAAAGPSPGSGPGDS(Phospho)PEGPEGEAPER_7779
7       .(Acetyl)AAAAAAGS(Phospho)GTPR_11113
8       .(Acetyl)AAAAAAGS(Phospho)GTPR_12224
9       .(Acetyl)AAAAAALSGAGT(Phospho)PPAGGGAGGGGAGGGGSPPGGWAVAR_18890
10      .(Acetyl)AAAAAALSGAGT(Phospho)PPAGGGAGGGGAGGGGSPPGGWAVAR_22224
11      .(Acetyl)AAAAAALSGAGTPPAGGGAGGGGAGGGGS(Phospho)PPGGWAVAR_24446
12      .(Acetyl)AAAETQS(Phospho)LR_28852
13      .(Acetyl)AAAETQS(Phospho)LR_28963
14      .(Acetyl)AAAVAAAGAGEPQS(Phospho)PDELLPK_31297
15      .(Acetyl)AAAVAAAGAGEPQS(Phospho)PDELLPK_31408
16      .(Acetyl)AADVSVTHRPPLS(Phospho)PK_33074
17      .(Acetyl)AADVSVTHRPPLS(Phospho)PK_33185
18      .(Acetyl)AAGGDHGS(Phospho)PDSYR_33741
19      .(Acetyl)AAGTAAALAFLS(Phospho)QES(Phospho)R_33852
20      .(Acetyl)AAGTAAALAFLS(Phospho)QES(Phospho)R_33852
21      .(Acetyl)AALHTTPDS(Phospho)PAAQLER_34741
22      .(Acetyl)AALHTTPDS(Phospho)PAAQLER_34852
23      .(Acetyl)AAPEEHDS(Phospho)PTEASQPIVEEEETK_35296
24      .(Acetyl)AAPEEHDS(Phospho)PTEASQPIVEEEETK_35629
25      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR_1114
26      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR_1114
27      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR_2225
28      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR_2225
29      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR_2447
30      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR_2447
⋮       ⋮
1397448 YSHSYLS(Phospho)DSDTEAK_28461
1397449 YSHSYLS(Phospho)DSDTEAK_28462
1397450 YSHSYLSDS(Phospho)DTEAK_28464
1397451 YSHSYLSDS(Phospho)DTEAK_28465
1397452 YSHSYLSDS(Phospho)DTEAK_28466
1397453 YSHSYLSDS(Phospho)DTEAK_28467
1397454 YSISLS(Phospho)PPEQQK_28472
1397455 YSKPTAPAPSAPPS(Phospho)PSAPEPPK_28475
1397456 YSPSQNS(Phospho)PIHHIPSR_28483
1397457 YSPSQNS(Phospho)PIHHIPSR_28486
1397458 YSPTS(Phospho)PK_28443
1397459 YSPTS(Phospho)PK_28488
1397460 YSPTS(Phospho)PK_28494
1397461 YSPTS(Phospho)PTYSPTSPK_28492
1397462 YSPTS(Phospho)PTYSPTSPK_28498
1397463 YSPTS(Phospho)PTYSPTTPK_28493
1397464 YSSGGNFET(Phospho)PSK_28529
1397465 YSSGGNFET(Phospho)PSK_28530
1397466 YTGEEDGAGGHS(Phospho)PAPPQTEEC(Carbamidomethyl)LR_28550
1397467 YVASYLLAALGGNSS(Phospho)PSAK_28561
1397468 YVASYLLAALGGNSS(Phospho)PSAK_28563
1397469 YVASYLLAALGGNSS(Phospho)PSAK_28565
1397470 YVDEENS(Phospho)DGETSNHR_28566
1397471 YVDEENS(Phospho)DGETSNHR_28567
1397472 YVGFGNT(Phospho)PPPQK_28572
1397473 YVPPHLS(Phospho)PDKK_28574
1397474 YWGPAS(Phospho)PTHK_28584
1397475 YWGPAS(Phospho)PTHK_28586
1397476 YYGGGS(Phospho)EGGR_28588
1397477 YYS(Phospho)IDDNQNK_28597
        site_id
1       EIF3J:O75822:S11
2       EIF3J:O75822:S13
3       EIF3J:O75822:S13
4       VPS51:Q9UID3:S10
5       VPS51:Q9UID3:S18
6       VPS51:Q9UID3:S18
7       POLE4:Q9NR33:S9
8       POLE4:Q9NR33:S9
9       FOXK2:Q01167:T13
10      FOXK2:Q01167:T13
11      FOXK2:Q01167:S30
12      PRPF4B:Q13523:S8
13      PRPF4B:Q13523:S8
14      TOMM22:Q9NS69:S15
15      TOMM22:Q9NS69:S15
16      RAVER1:Q8IY67:S14
17      RAVER1:Q8IY67:S14
18      ADSL:P30566:S9
19      NPM3:O75607:S16
20      NPM3:O75607:S13
21      ZNF316:A6NFI3:S10
22      ZNF316:A6NFI3:S10
23      DDX47:Q9H0S4:S9
24      DDX47:Q9H0S4:S9
25      KAT8:Q9H7Z6:S37
26      KAT8:Q9H7Z6:S42
27      KAT8:Q9H7Z6:S37
28      KAT8:Q9H7Z6:S42
29      KAT8:Q9H7Z6:S42
30      KAT8:Q9H7Z6:S37
⋮       ⋮
1397448 MYO18A:Q92614:S2041
1397449 MYO18A:Q92614:S2041
1397450 MYO18A:Q92614:S2043
1397451 MYO18A:Q92614:S2043
1397452 MYO18A:Q92614:S2043
1397453 MYO18A:Q92614:S2043
1397454 ACAP2:Q15057:S521
1397455 MLLT6:P55198:S382
1397456 BCLAF1:Q9NYF8:S290
1397457 BCLAF1:Q9NYF8:S290
1397458 POLR2A:P24928:S1864
1397459 POLR2A:P24928:S1864
1397460 POLR2A:P24928:S1864
1397461 POLR2A:P24928:S1913
1397462 POLR2A:P24928:S1913
1397463 POLR2A:P24928:S1878
1397464 OCLN:Q16625:T376
1397465 OCLN:Q16625:T376
1397466 RECQL5:O94762:S815
1397467 RPLP2:P05387:S17
1397468 RPLP2:P05387:S17
1397469 RPLP2:P05387:S17
1397470 KRI1:Q8N9T8:S136
1397471 KRI1:Q8N9T8:S136
1397472 ARFGAP1:Q8N6T3:T189
1397473 PARG:Q86W56:S448
1397474 EPS8L2:Q9H6S3:S570
1397475 EPS8L2:Q9H6S3:S570
1397476 HNRNPL:P14866:S52
1397477 NCOA7:Q8NI08:S89
        modified_peptide_sequence
1       .(Acetyl)AAAAAAAGDS(Phospho)DS(Phospho)WDADAFSVEDPVRK
2       .(Acetyl)AAAAAAAGDS(Phospho)DS(Phospho)WDADAFSVEDPVRK
3       .(Acetyl)AAAAAAAGDSDS(Phospho)WDADAFSVEDPVR
4       .(Acetyl)AAAAAAGPS(Phospho)PGSGPGDS(Phospho)PEGPEGEAPER
5       .(Acetyl)AAAAAAGPS(Phospho)PGSGPGDS(Phospho)PEGPEGEAPER
6       .(Acetyl)AAAAAAGPSPGSGPGDS(Phospho)PEGPEGEAPER
7       .(Acetyl)AAAAAAGS(Phospho)GTPR
8       .(Acetyl)AAAAAAGS(Phospho)GTPR
9       .(Acetyl)AAAAAALSGAGT(Phospho)PPAGGGAGGGGAGGGGSPPGGWAVAR
10      .(Acetyl)AAAAAALSGAGT(Phospho)PPAGGGAGGGGAGGGGSPPGGWAVAR
11      .(Acetyl)AAAAAALSGAGTPPAGGGAGGGGAGGGGS(Phospho)PPGGWAVAR
12      .(Acetyl)AAAETQS(Phospho)LR
13      .(Acetyl)AAAETQS(Phospho)LR
14      .(Acetyl)AAAVAAAGAGEPQS(Phospho)PDELLPK
15      .(Acetyl)AAAVAAAGAGEPQS(Phospho)PDELLPK
16      .(Acetyl)AADVSVTHRPPLS(Phospho)PK
17      .(Acetyl)AADVSVTHRPPLS(Phospho)PK
18      .(Acetyl)AAGGDHGS(Phospho)PDSYR
19      .(Acetyl)AAGTAAALAFLS(Phospho)QES(Phospho)R
20      .(Acetyl)AAGTAAALAFLS(Phospho)QES(Phospho)R
21      .(Acetyl)AALHTTPDS(Phospho)PAAQLER
22      .(Acetyl)AALHTTPDS(Phospho)PAAQLER
23      .(Acetyl)AAPEEHDS(Phospho)PTEASQPIVEEEETK
24      .(Acetyl)AAPEEHDS(Phospho)PTEASQPIVEEEETK
25      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR
26      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR
27      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR
28      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR
29      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR
30      .(Acetyl)AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPS(Phospho)PGRVS(Phospho)PPTPAR
⋮       ⋮
1397448 YSHSYLS(Phospho)DSDTEAK
1397449 YSHSYLS(Phospho)DSDTEAK
1397450 YSHSYLSDS(Phospho)DTEAK
1397451 YSHSYLSDS(Phospho)DTEAK
1397452 YSHSYLSDS(Phospho)DTEAK
1397453 YSHSYLSDS(Phospho)DTEAK
1397454 YSISLS(Phospho)PPEQQK
1397455 YSKPTAPAPSAPPS(Phospho)PSAPEPPK
1397456 YSPSQNS(Phospho)PIHHIPSR
1397457 YSPSQNS(Phospho)PIHHIPSR
1397458 YSPTS(Phospho)PK
1397459 YSPTS(Phospho)PK
1397460 YSPTS(Phospho)PK
1397461 YSPTS(Phospho)PTYSPTSPK
1397462 YSPTS(Phospho)PTYSPTSPK
1397463 YSPTS(Phospho)PTYSPTTPK
1397464 YSSGGNFET(Phospho)PSK
1397465 YSSGGNFET(Phospho)PSK
1397466 YTGEEDGAGGHS(Phospho)PAPPQTEEC(Carbamidomethyl)LR
1397467 YVASYLLAALGGNSS(Phospho)PSAK
1397468 YVASYLLAALGGNSS(Phospho)PSAK
1397469 YVASYLLAALGGNSS(Phospho)PSAK
1397470 YVDEENS(Phospho)DGETSNHR
1397471 YVDEENS(Phospho)DGETSNHR
1397472 YVGFGNT(Phospho)PPPQK
1397473 YVPPHLS(Phospho)PDKK
1397474 YWGPAS(Phospho)PTHK
1397475 YWGPAS(Phospho)PTHK
1397476 YYGGGS(Phospho)EGGR
1397477 YYS(Phospho)IDDNQNK
        peptide_sequence                                phosphosite
1       AAAAAAAGDSDSWDADAFSVEDPVRK                      S11
2       AAAAAAAGDSDSWDADAFSVEDPVRK                      S13
3       AAAAAAAGDSDSWDADAFSVEDPVR                       S13
4       AAAAAAGPSPGSGPGDSPEGPEGEAPER                    S10
5       AAAAAAGPSPGSGPGDSPEGPEGEAPER                    S18
6       AAAAAAGPSPGSGPGDSPEGPEGEAPER                    S18
7       AAAAAAGSGTPR                                    S9
8       AAAAAAGSGTPR                                    S9
9       AAAAAALSGAGTPPAGGGAGGGGAGGGGSPPGGWAVAR          T13
10      AAAAAALSGAGTPPAGGGAGGGGAGGGGSPPGGWAVAR          T13
11      AAAAAALSGAGTPPAGGGAGGGGAGGGGSPPGGWAVAR          S30
12      AAAETQSLR                                       S8
13      AAAETQSLR                                       S8
14      AAAVAAAGAGEPQSPDELLPK                           S15
15      AAAVAAAGAGEPQSPDELLPK                           S15
16      AADVSVTHRPPLSPK                                 S14
17      AADVSVTHRPPLSPK                                 S14
18      AAGGDHGSPDSYR                                   S9
19      AAGTAAALAFLSQESR                                S16
20      AAGTAAALAFLSQESR                                S13
21      AALHTTPDSPAAQLER                                S10
22      AALHTTPDSPAAQLER                                S10
23      AAPEEHDSPTEASQPIVEEEETK                         S9
24      AAPEEHDSPTEASQPIVEEEETK                         S9
25      AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPSPGRVSPPTPAR S37
26      AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPSPGRVSPPTPAR S42
27      AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPSPGRVSPPTPAR S37
28      AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPSPGRVSPPTPAR S42
29      AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPSPGRVSPPTPAR S42
30      AAQGAAAAVAAGTSGVAGEGEPGPGENAAAEGTAPSPGRVSPPTPAR S37
⋮       ⋮                                               ⋮
1397448 YSHSYLSDSDTEAK                                  S2041
1397449 YSHSYLSDSDTEAK                                  S2041
1397450 YSHSYLSDSDTEAK                                  S2043
1397451 YSHSYLSDSDTEAK                                  S2043
1397452 YSHSYLSDSDTEAK                                  S2043
1397453 YSHSYLSDSDTEAK                                  S2043
1397454 YSISLSPPEQQK                                    S521
1397455 YSKPTAPAPSAPPSPSAPEPPK                          S382
1397456 YSPSQNSPIHHIPSR                                 S290
1397457 YSPSQNSPIHHIPSR                                 S290
1397458 YSPTSPK                                         S1864
1397459 YSPTSPK                                         S1864
1397460 YSPTSPK                                         S1864
1397461 YSPTSPTYSPTSPK                                  S1913
1397462 YSPTSPTYSPTSPK                                  S1913
1397463 YSPTSPTYSPTTPK                                  S1878
1397464 YSSGGNFETPSK                                    T376
1397465 YSSGGNFETPSK                                    T376
1397466 YTGEEDGAGGHSPAPPQTEECLR                         S815
1397467 YVASYLLAALGGNSSPSAK                             S17
1397468 YVASYLLAALGGNSSPSAK                             S17
1397469 YVASYLLAALGGNSSPSAK                             S17
1397470 YVDEENSDGETSNHR                                 S136
1397471 YVDEENSDGETSNHR                                 S136
1397472 YVGFGNTPPPQK                                    T189
1397473 YVPPHLSPDKK                                     S448
1397474 YWGPASPTHK                                      S570
1397475 YWGPASPTHK                                      S570
1397476 YYGGGSEGGR                                      S52
1397477 YYSIDDNQNK                                      S89
        peptide_intensity cell_code drug_code time_point cell_line drug
1        1.9454891        H508      AL        1h         NCI-H508  alpelisib
2        1.9454891        H508      AL        1h         NCI-H508  alpelisib
3        3.3799950        H508      AL        1h         NCI-H508  alpelisib
4        1.0473535        H508      AL        1h         NCI-H508  alpelisib
5        1.0473535        H508      AL        1h         NCI-H508  alpelisib
6        1.0487342        H508      AL        1h         NCI-H508  alpelisib
7        0.8299349        H508      AL        1h         NCI-H508  alpelisib
8        0.2730009        H508      AL        1h         NCI-H508  alpelisib
9        1.3650722        H508      AL        1h         NCI-H508  alpelisib
10       1.3650722        H508      AL        1h         NCI-H508  alpelisib
11       3.2477467        H508      AL        1h         NCI-H508  alpelisib
12      -0.9380059        H508      AL        1h         NCI-H508  alpelisib
13      -0.8326142        H508      AL        1h         NCI-H508  alpelisib
14      -1.3197837        H508      AL        1h         NCI-H508  alpelisib
15      -1.5597104        H508      AL        1h         NCI-H508  alpelisib
16       2.6147567        H508      AL        1h         NCI-H508  alpelisib
17       5.4233211        H508      AL        1h         NCI-H508  alpelisib
18       0.2140166        H508      AL        1h         NCI-H508  alpelisib
19      -2.7354259        H508      AL        1h         NCI-H508  alpelisib
20      -2.7354259        H508      AL        1h         NCI-H508  alpelisib
21       3.0433889        H508      AL        1h         NCI-H508  alpelisib
22       3.3258466        H508      AL        1h         NCI-H508  alpelisib
23       2.5643931        H508      AL        1h         NCI-H508  alpelisib
24       2.5643931        H508      AL        1h         NCI-H508  alpelisib
25       3.1220227        H508      AL        1h         NCI-H508  alpelisib
26       3.1220227        H508      AL        1h         NCI-H508  alpelisib
27       2.7523772        H508      AL        1h         NCI-H508  alpelisib
28       2.7523772        H508      AL        1h         NCI-H508  alpelisib
29       2.7523772        H508      AL        1h         NCI-H508  alpelisib
30       2.7523772        H508      AL        1h         NCI-H508  alpelisib
⋮       ⋮                 ⋮         ⋮         ⋮          ⋮         ⋮
1397448 -1.2600359        SNU       WI        96h        SNU-61    WIKI4
1397449 -1.2600359        SNU       WI        96h        SNU-61    WIKI4
1397450 -1.9202480        SNU       WI        96h        SNU-61    WIKI4
1397451 -1.5417633        SNU       WI        96h        SNU-61    WIKI4
1397452 -1.8841331        SNU       WI        96h        SNU-61    WIKI4
1397453 -1.7976526        SNU       WI        96h        SNU-61    WIKI4
1397454  1.6515034        SNU       WI        96h        SNU-61    WIKI4
1397455 -0.4049861        SNU       WI        96h        SNU-61    WIKI4
1397456  1.4835343        SNU       WI        96h        SNU-61    WIKI4
1397457  1.5008544        SNU       WI        96h        SNU-61    WIKI4
1397458 -1.3078728        SNU       WI        96h        SNU-61    WIKI4
1397459  1.2480231        SNU       WI        96h        SNU-61    WIKI4
1397460  1.2676005        SNU       WI        96h        SNU-61    WIKI4
1397461  1.2935214        SNU       WI        96h        SNU-61    WIKI4
1397462  1.4467678        SNU       WI        96h        SNU-61    WIKI4
1397463  1.1779315        SNU       WI        96h        SNU-61    WIKI4
1397464 -1.6786497        SNU       WI        96h        SNU-61    WIKI4
1397465 -1.6642524        SNU       WI        96h        SNU-61    WIKI4
1397466  1.5653991        SNU       WI        96h        SNU-61    WIKI4
1397467  1.9887312        SNU       WI        96h        SNU-61    WIKI4
1397468  1.9887312        SNU       WI        96h        SNU-61    WIKI4
1397469  1.6096674        SNU       WI        96h        SNU-61    WIKI4
1397470 -1.1546550        SNU       WI        96h        SNU-61    WIKI4
1397471 -1.1873518        SNU       WI        96h        SNU-61    WIKI4
1397472  0.9997610        SNU       WI        96h        SNU-61    WIKI4
1397473 -3.1446121        SNU       WI        96h        SNU-61    WIKI4
1397474  3.0819859        SNU       WI        96h        SNU-61    WIKI4
1397475  3.0692578        SNU       WI        96h        SNU-61    WIKI4
1397476 -4.0146677        SNU       WI        96h        SNU-61    WIKI4
1397477 -2.7246166        SNU       WI        96h        SNU-61    WIKI4

In [27]:
vpmx_by_cell_line <- lapply(sort(unique(dt$cell_line)), function(cl) {
  message("mVESPA: ", cl)

  get_vpmx(
    osw       = dt[cell_line == cl],
    spregulon = spregulon,
    aregulon  = aregulon,
    library   = library
  )
})

names(vpmx_by_cell_line) <- sort(unique(dt$cell_line))

mVESPA: HCT


Computing the association scores


Computing the association scores

Loading FASTA DB


Computing the association scores

mVESPA: HT115


Computing the association scores


Computing the association scores

Loading FASTA DB


Computing the association scores

mVESPA: LS1034


Computing the association scores


Computing the association scores

Loading FASTA DB


Computing the association scores

mVESPA: MDST8


Computing the association scores


Computing the association scores

Loading FASTA DB


Computing the association scores

mVESPA: NCI-H508


Computing the association scores


Computing the association scores

Loading FASTA DB


Computing the association scores

mVESPA: SNU-61


Computing the association scores


Computing the association scores

Loading FASTA DB


Computing the association scores

In [29]:
dir.create("./data/u54-dp/processed")

In [31]:
saveRDS(vpmx_by_cell_line, "./data/u54-dp/processed/u54-dp_mvespa.rds")