# 00-4. Preprocessing (PXD048532)

In [20]:
library(data.table)
library(readxl)
library(dplyr)
library(tidyr)
library(tibble)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [3]:
if (!file.exists("./tools/references/library.fasta")) {
  out <- system2(
    "bash",
    "./tools/scripts/fasta.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

In [26]:
xlsx <- "./data/pxd048532/adk0850_data_s4.xlsx"
meta <- read_xlsx(xlsx, sheet="Supplemental_table_S5_G12Ci_met")
meta

      id    Uniprot_ID
1      0    A0A096LP49
2      1    A0A0A6YYK7
3      4    A0A0B4J2F2
4      5    A0A0B4J2F2
5      6    A0A0J9YXV3
6      7    A0A1B0GVM5
7      8    Q12774
8      9    Q12774
9     10    Q12774
10    11    Q12774
11    12    Q12774
12    14    Q12774
13    16    Q12774
14    17    Q12774
15    18    Q12774
16    19    Q12774
17    20    Q12774
18    21    A0A3B3IU46
19    22    A0A590UK10
20    24    A0A590UK10
21    25    A0A590UK10
22    26    A0A590UK10
23    27    A0A590UK10
24    28    A0A590UK10
25    29    A0AVK6
26    30    A0AVK6
27    31    A0AVK6
28    32    A0AVK6
29    33    A0AVT1
30    34    A0FGR8
⋮     ⋮     ⋮
20206 28291 Q9NSK0
20207 28292 Q9NTZ6
20208 28294 Q9NX63
20209 28296 Q9NY59
20210 28297 Q9NYB9
20211 28298 Q9NYF8
20212 28301 Q9NYF8
20213 28304 Q9NYV4
20214 28309 Q9NZM3
20215 28314 Q9UBS9
20216 28315 Q9UDY2
20217 28316 Q9UDY2
20218 28317 Q9UDY2
20219 28318 Q9UDY2
20220 28319 Q9UDY2
20221 28321 Q9UHB7
20222 28328 Q9UKJ3
20223 28329 Q9UKP5
20224 28331 Q9ULC8
20225 28334 Q9UMY4
20226 28340 Q9UPZ9
20227 28341 Q9UQ35
20228 28342 Q9UQ35
20229 28346 Q9UQR0
20230 28347 Q9Y2U5
20231 28348 Q9Y2W1
20232 28351 Q9Y2W2
20233 28352 Q9Y2X7
20234 28353 Q9Y446
20235 28354 Q9Y446
      Description
1     Rho guanine nucleotide exchange factor 5
2     Rho guanine nucleotide exchange factor 5
3     Serine/threonine-protein kinase SIK1
4     Serine/threonine-protein kinase SIK1
5     Rho guanine nucleotide exchange factor 5
6     Rho guanine nucleotide exchange factor 5
7     Rho guanine nucleotide exchange factor 5
8     Rho guanine nucleotide exchange factor 5
9     Rho guanine nucleotide exchange factor 5
10    Rho guanine nucleotide exchange factor 5
11    Rho guanine nucleotide exchange factor 5
12    Rho guanine nucleotide exchange factor 5
13    Rho guanine nucleotide exchange factor 5
14    Rho guanine nucleotide exchange factor 5
15    Rho guanine nucleotide exchange factor 5
16    Rho guanine nucleotide exchange factor 5
17    Rho guanine nucleotide exchange factor 5
18    RNMT-activating mini protein
19    Rho guanine nucleotide exchange factor 18
20    Rho guanine nucleotide exchange factor 18
21    Rho guanine nucleotide exchange factor 18
22    Rho guanine nucleotide exchange factor 18
23    Rho guanine nucleotide exchange factor 18
24    Rho guanine nucleotide exchange factor 18
25    Transcription factor E2F8
26    Transcription factor E2F8
27    Transcription factor E2F8
28    Transcription factor E2F8
29    Ubiquitin-like modifier-activating enzyme 6
30    Extended synaptotagmin-2
⋮     ⋮
20206 Kinesin light chain 4
20207 RNA-binding protein 12
20208 MICOS complex subunit MIC19
20209 Sphingomyelin phosphodiesterase 3
20210 Abl interactor 2
20211 Bcl-2-associated transcription factor 1
20212 Bcl-2-associated transcription factor 1
20213 Cyclin-dependent kinase 12
20214 Intersectin-2
20215 SUN domain-containing ossification factor
20216 Tight junction protein ZO-2
20217 Tight junction protein ZO-2
20218 Tight junction protein ZO-2
20219 Tight junction protein ZO-2
20220 Tight junction protein ZO-2
20221 AF4/FMR2 family member 4
20222 G patch domain-containing protein 8
20223 A disintegrin and metalloproteinase with thrombospondin motifs 6
20224 Probable palmitoyltransferase ZDHHC8
20225 Sorting nexin-12
20226 Serine/threonine-protein kinase ICK
20227 Serine/arginine repetitive matrix protein 2
20228 Serine/arginine repetitive matrix protein 2
20229 Sex comb on midleg-like protein 2
20230 Mitogen-activated protein kinase kinase kinase 2
20231 Thyroid hormone receptor-associated protein 3
20232 WW domain-binding protein 11
20233 ARF GTPase-activating protein GIT1
20234 Plakophilin-3
20235 Plakophilin-3
      Gene_name    Protein_group_IDs Position
1     MGC50722     0                  478
2     TRAV19       1                   62
3     LOC102724428 3                  575
4     LOC102724428 3                  534
5     GREP1        4                  508
6     ETDC         7                   52
7     ARHGEF5      8                  445
8     ARHGEF5      8                  450
9     ARHGEF5      8                  452
10    ARHGEF5      8                 1004
11    ARHGEF5      8                   11
12    ARHGEF5      8                 1126
13    ARHGEF5      8                  610
14    ARHGEF5      8                 1405
15    ARHGEF5      8                  897
16    ARHGEF5      8                  983
17    ARHGEF5      8                  184
18    FAM103A1     10                  36
19    ARHGEF18     11                 694
20    ARHGEF18     11                1058
21    ARHGEF18     11                 667
22    ARHGEF18     11                1035
23    ARHGEF18     11                1037
24    ARHGEF18     11                1010
25    E2F8         15                 664
26    E2F8         15                 413
27    E2F8         15                 416
28    E2F8         15                 417
29    UBA6         16                  36
30    ESYT2        17                 755
⋮     ⋮            ⋮                 ⋮
20206 KLC4         5408               593
20207 RBM12        5419               433
20208 CHCHD3       5506                49
20209 SMPD3        5529               212
20210 ABI2         5534               198
20211 BCLAF1       5536               383
20212 BCLAF1       5536               284
20213 CDK12        5548               279
20214 ITSN2        5573               968
20215 SUCO         5683              1095
20216 TJP2         5698               269
20217 TJP2         5698              1166
20218 TJP2         5698              1118
20219 TJP2         5698               426
20220 TJP2         5698               428
20221 AFF4         5731               712
20222 GPATCH8      5811              1038
20223 ADAMTS6      5820               451
20224 ZDHHC8       5837               541
20225 SNX12        5890                72
20226 ICK          5943               159
20227 SRRM2        5946              2693
20228 SRRM2        5946              1820
20229 SCML2        5956               506
20230 MAP3K2       6024               240
20231 THRAP3       6027               873
20232 WBP11        6028               236
20233 GIT1         6032               598
20234 PKP3         6083               176
20235 PKP3         6083               195
      Fasta_headers
1     sp|A0A096LP49|CC187_HUMAN Coiled-coil domain-containing protein 187 OS=Homo sapiens OX=9606 GN=CCDC187 PE=2 SV=1
2     sp|A0A0A6YYK7|TVA19_HUMAN T cell receptor alpha variable 19 OS=Homo sapiens OX=9606 GN=TRAV19 PE=2 SV=5
3     sp|A0A0B4J2F2|SIK1B_HUMAN Putative serine/threonine-protein kinase SIK1B OS=Homo sapiens OX=9606 GN=SIK1B PE=5 SV=1;sp|P57059|SIK1_HUMAN Serine/threonine-protein kinase SIK1 OS=Homo sapiens OX=9606 GN=SIK1 PE=1 SV=2
4     sp|A0A0B4J2F2|SIK1B_HUMAN Putative serine/threonine-protein kinase SIK1B OS=Homo sapiens OX=9606 GN=SIK1B PE=5 SV=1;sp|P57059|SIK1_HUMAN Serine/threonine-protein kinase SIK1 OS=Homo sapiens OX=9606 GN=SIK1 PE=1 SV=2
5     sp|A0A0J9YXV3|GREP1_HUMAN Glycine-rich extracellular protein 1 OS=Homo sapiens OX=9606 GN=GREP1 PE=3 SV=1
6     sp|A0A1B0GVM5|ETDC_HUMAN Embryonic testis differentiation protein homolog C OS=Homo sapiens OX=9606 GN=ETDC PE=4 SV=1
7     sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1;tr|A0A5F9ZGZ6|A0A5F9ZGZ6_HUMAN Rho guanine nucleotide
8     sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1;tr|A0A5F9ZGZ6|A0A5F9ZGZ6_HUMAN Rho guanine nucleotide
9     sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1;tr|A0A5F9ZGZ6|A0A5F9ZGZ6_HUMAN Rho guanine nucleotide
10    sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1
11    sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1;tr|A0A5F9ZGZ6|A0A5F9ZGZ6_HUMAN Rho guanine nucleotide
12    sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1
13    sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1
14    sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1
15    sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1
16    sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1
17    sp|Q12774|ARHG5_HUMAN Rho guanine nucleotide exchange factor 5 OS=Homo sapiens OX=9606 GN=ARHGEF5 PE=1 SV=3;tr|A0A2R8YFR7|A0A2R8YFR7_HUMAN DH domain-containing protein OS=Homo sapiens OX=9606 PE=4 SV=1;tr|A0A5F9ZGZ6|A0A5F9ZGZ6_HUMAN Rho guanine nucleotide
18    sp|A0A3B3IU46|RMACL_HUMAN RNA guanine-N7 methyltransferase-activating subunit-like protein OS=Homo sapiens OX=9606 GN=RAMACL PE=3 SV=1;sp|Q9BTL3|RAMAC_HUMAN RNA guanine-N7 methyltransferase activating subunit OS=Homo sapiens OX=9606 GN=RAMAC PE=1 SV=1
19    tr|A0A590UK10|A0A590UK10_HUMAN Rho guanine nucleotide exchange factor 18 (Fragment) OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=4 SV=1;sp|Q6ZSZ5|ARHGI_HUMAN Rho guanine nucleotide exchange factor 18 OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=1 SV=4
20    tr|A0A590UK10|A0A590UK10_HUMAN Rho guanine nucleotide exchange factor 18 (Fragment) OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=4 SV=1;sp|Q6ZSZ5|ARHGI_HUMAN Rho guanine nucleotide exchange factor 18 OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=1 SV=4
21    tr|A0A590UK10|A0A590UK10_HUMAN Rho guanine nucleotide exchange factor 18 (Fragment) OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=4 SV=1;sp|Q6ZSZ5|ARHGI_HUMAN Rho guanine nucleotide exchange factor 18 OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=1 SV=4
22    tr|A0A590UK10|A0A590UK10_HUMAN Rho guanine nucleotide exchange factor 18 (Fragment) OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=4 SV=1;sp|Q6ZSZ5|ARHGI_HUMAN Rho guanine nucleotide exchange factor 18 OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=1 SV=4
23    tr|A0A590UK10|A0A590UK10_HUMAN Rho guanine nucleotide exchange factor 18 (Fragment) OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=4 SV=1;sp|Q6ZSZ5|ARHGI_HUMAN Rho guanine nucleotide exchange factor 18 OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=1 SV=4
24    tr|A0A590UK10|A0A590UK10_HUMAN Rho guanine nucleotide exchange factor 18 (Fragment) OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=4 SV=1;sp|Q6ZSZ5|ARHGI_HUMAN Rho guanine nucleotide exchange factor 18 OS=Homo sapiens OX=9606 GN=ARHGEF18 PE=1 SV=4
25    sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8 OS=Homo sapiens OX=9606 GN=E2F8 PE=1 SV=1
26    sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8 OS=Homo sapiens OX=9606 GN=E2F8 PE=1 SV=1
27    sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8 OS=Homo sapiens OX=9606 GN=E2F8 PE=1 SV=1
28    sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8 OS=Homo sapiens OX=9606 GN=E2F8 PE=1 SV=1
29    sp|A0AVT1|UBA6_HUMAN Ubiquitin-like modifier-activating enzyme 6 OS=Homo sapiens OX=9606 GN=UBA6 PE=1 SV=1
30    sp|A0FGR8|ESYT2_HUMAN Extended synaptotagmin-2 OS=Homo sapiens OX=9606 GN=ESYT2 PE=1 SV=1
⋮     ⋮
20206 sp|Q9NSK0|KLC4_HUMAN Kinesin light chain 4 OS=Homo sapiens OX=9606 GN=KLC4 PE=1 SV=3
20207 sp|Q9NTZ6|RBM12_HUMAN RNA-binding protein 12 OS=Homo sapiens OX=9606 GN=RBM12 PE=1 SV=1
20208 sp|Q9NX63|MIC19_HUMAN MICOS complex subunit MIC19 OS=Homo sapiens OX=9606 GN=CHCHD3 PE=1 SV=1
20209 sp|Q9NY59|NSMA2_HUMAN Sphingomyelin phosphodiesterase 3 OS=Homo sapiens OX=9606 GN=SMPD3 PE=1 SV=1
20210 sp|Q9NYB9|ABI2_HUMAN Abl interactor 2 OS=Homo sapiens OX=9606 GN=ABI2 PE=1 SV=1
20211 sp|Q9NYF8|BCLF1_HUMAN Bcl-2-associated transcription factor 1 OS=Homo sapiens OX=9606 GN=BCLAF1 PE=1 SV=2
20212 sp|Q9NYF8|BCLF1_HUMAN Bcl-2-associated transcription factor 1 OS=Homo sapiens OX=9606 GN=BCLAF1 PE=1 SV=2
20213 sp|Q9NYV4|CDK12_HUMAN Cyclin-dependent kinase 12 OS=Homo sapiens OX=9606 GN=CDK12 PE=1 SV=2
20214 sp|Q9NZM3|ITSN2_HUMAN Intersectin-2 OS=Homo sapiens OX=9606 GN=ITSN2 PE=1 SV=3
20215 sp|Q9UBS9|SUCO_HUMAN SUN domain-containing ossification factor OS=Homo sapiens OX=9606 GN=SUCO PE=1 SV=1
20216 sp|Q9UDY2|ZO2_HUMAN Tight junction protein ZO-2 OS=Homo sapiens OX=9606 GN=TJP2 PE=1 SV=2
20217 sp|Q9UDY2|ZO2_HUMAN Tight junction protein ZO-2 OS=Homo sapiens OX=9606 GN=TJP2 PE=1 SV=2
20218 sp|Q9UDY2|ZO2_HUMAN Tight junction protein ZO-2 OS=Homo sapiens OX=9606 GN=TJP2 PE=1 SV=2
20219 sp|Q9UDY2|ZO2_HUMAN Tight junction protein ZO-2 OS=Homo sapiens OX=9606 GN=TJP2 PE=1 SV=2
20220 sp|Q9UDY2|ZO2_HUMAN Tight junction protein ZO-2 OS=Homo sapiens OX=9606 GN=TJP2 PE=1 SV=2
20221 sp|Q9UHB7|AFF4_HUMAN AF4/FMR2 family member 4 OS=Homo sapiens OX=9606 GN=AFF4 PE=1 SV=1
20222 sp|Q9UKJ3|GPTC8_HUMAN G patch domain-containing protein 8 OS=Homo sapiens OX=9606 GN=GPATCH8 PE=1 SV=2
20223 sp|Q9UKP5|ATS6_HUMAN A disintegrin and metalloproteinase with thrombospondin motifs 6 OS=Homo sapiens OX=9606 GN=ADAMTS6 PE=2 SV=2
20224 sp|Q9ULC8|ZDHC8_HUMAN Palmitoyltransferase ZDHHC8 OS=Homo sapiens OX=9606 GN=ZDHHC8 PE=1 SV=3
20225 sp|Q9UMY4|SNX12_HUMAN Sorting nexin-12 OS=Homo sapiens OX=9606 GN=SNX12 PE=1 SV=4
20226 sp|Q9UPZ9|CILK1_HUMAN Serine/threonine-protein kinase ICK OS=Homo sapiens OX=9606 GN=CILK1 PE=1 SV=1
20227 sp|Q9UQ35|SRRM2_HUMAN Serine/arginine repetitive matrix protein 2 OS=Homo sapiens OX=9606 GN=SRRM2 PE=1 SV=2
20228 sp|Q9UQ35|SRRM2_HUMAN Serine/arginine repetitive matrix protein 2 OS=Homo sapiens OX=9606 GN=SRRM2 PE=1 SV=2
20229 sp|Q9UQR0|SCML2_HUMAN Sex comb on midleg-like protein 2 OS=Homo sapiens OX=9606 GN=SCML2 PE=1 SV=1
20230 sp|Q9Y2U5|M3K2_HUMAN Mitogen-activated protein kinase kinase kinase 2 OS=Homo sapiens OX=9606 GN=MAP3K2 PE=1 SV=2
20231 sp|Q9Y2W1|TR150_HUMAN Thyroid hormone receptor-associated protein 3 OS=Homo sapiens OX=9606 GN=THRAP3 PE=1 SV=2
20232 sp|Q9Y2W2|WBP11_HUMAN WW domain-binding protein 11 OS=Homo sapiens OX=9606 GN=WBP11 PE=1 SV=1
20233 sp|Q9Y2X7|GIT1_HUMAN ARF GTPase-activating protein GIT1 OS=Homo sapiens OX=9606 GN=GIT1 PE=1 SV=2
20234 sp|Q9Y446|PKP3_HUMAN Plakophilin-3 OS=Homo sapiens OX=9606 GN=PKP3 PE=1 SV=1
20235 sp|Q9Y446|PKP3_HUMAN Plakophilin-3 OS=Homo sapiens OX=9606 GN=PKP3 PE=1 SV=1
      Localization_prob PEP          Score   ⋯ Number_of_Phospho_(STY)
1     0.997241           5.69872e-04  47.476 ⋯ 1
2     1.000000           5.92316e-03  40.725 ⋯ 1
3     0.911043           1.40435e-05  71.497 ⋯ 1
4     0.973662           4.15665e-10  50.980 ⋯ 1
5     1.000000           2.29371e-02  42.068 ⋯ 1
6     0.897359           6.22036e-02  55.503 ⋯ 1
7     0.999999           3.19872e-36 128.090 ⋯ 1;2
8     0.998142          3.79655e-115 221.440 ⋯ 1;2
9     0.843071           1.03232e-35 120.590 ⋯ 1
10    0.969092           2.47336e-03  82.529 ⋯ 1
11    0.999578           3.95583e-68 140.630 ⋯ 1
12    0.967038           8.99449e-69 198.250 ⋯ 1
13    0.851435           4.50034e-03  67.081 ⋯ 1
14    0.999896           2.60530e-30 150.290 ⋯ 1
15    0.925109           1.02734e-04 139.540 ⋯ 1
16    0.999988           2.62192e-46 124.910 ⋯ 1
17    0.792286           4.59284e-19  72.754 ⋯ 1
18    1.000000           1.54620e-27 139.210 ⋯ 1
19    1.000000           4.29622e-03  68.563 ⋯ 1
20    0.998571           1.40891e-15  50.572 ⋯ 1
21    0.992669           2.82502e-28 139.110 ⋯ 1
22    0.841727           4.34209e-07 150.180 ⋯ 1
23    0.979681           4.13623e-05 125.180 ⋯ 1
24    0.970807           2.36061e-03  61.523 ⋯ 1
25    0.999658           1.09572e-06  78.469 ⋯ 1
26    0.963104           3.99080e-03  43.713 ⋯ 2
27    0.836432           3.99080e-03  43.713 ⋯ 2
28    0.932842           9.30401e-06 106.930 ⋯ 1
29    0.999409           1.04529e-57 165.180 ⋯ 1
30    0.928956           5.23454e-49 138.640 ⋯ 1
⋮     ⋮                 ⋮            ⋮       ⋱ ⋮
20206 0.859742          7.18294e-182 243.160 ⋯ 1
20207 0.999993           4.89969e-09  83.375 ⋯ 2
20208 0.792279           9.14234e-52 160.080 ⋯ 1
20209 0.941465           3.56868e-02  83.429 ⋯ 1
20210 0.885321           1.52844e-04  79.705 ⋯ 1
20211 0.971023          1.48798e-150 231.830 ⋯ 1;2
20212 0.837241           3.40215e-38 168.910 ⋯ 1;2
20213 0.959968           5.76533e-03  42.232 ⋯ 2
20214 1.000000           3.65987e-14 110.170 ⋯ 1
20215 0.875274           6.10910e-08  63.185 ⋯ 1
20216 0.991312           4.16738e-03 106.940 ⋯ 1
20217 0.920735           2.21900e-56 119.870 ⋯ 1
20218 1.000000           1.58068e-03  49.742 ⋯ 1
20219 0.908236           1.63791e-19  94.975 ⋯ 2
20220 0.874390           1.91694e-24 118.000 ⋯ 2
20221 0.993673           2.97151e-05  47.933 ⋯ 2
20222 0.988405           2.83436e-04  65.942 ⋯ 2
20223 0.994230           2.73825e-02  41.956 ⋯ 3
20224 0.997913           1.02049e-03  48.444 ⋯ 2
20225 0.807526           5.86676e-03  87.123 ⋯ 1
20226 0.994234           1.20407e-09  85.478 ⋯ 1;2
20227 0.767399           5.36180e-05 118.810 ⋯ 1;2;3
20228 0.960688           2.29870e-11 132.380 ⋯ 1;2;3
20229 0.849832           2.68967e-04  40.252 ⋯ 1
20230 0.758833           7.22347e-66 157.080 ⋯ 1
20231 0.827708           3.69459e-06  95.022 ⋯ 1
20232 0.838354           1.78821e-14  89.467 ⋯ 1
20233 0.920086           1.17239e-40 108.650 ⋯ 2
20234 0.999525           3.26750e-05 143.910 ⋯ 1
20235 0.793883           1.32718e-13  46.697 ⋯ 2
      Amino_acid Sequence_window
1     S          AWGAQGQDRSFQRPESPHERLGHFSQRPWSA
2     S          TRDTTYYLFWYKQPPSGELVFLIRRNSFDEQ
3     S          GAVLLPVSFQEGRRASDTSLTQGLKAFRQQL
4     S          GLSGTPATQGLLGACSPVRLASPFLGSQSAT
5     S          LKPGYQAGDEYAEARSQPGGPDVKRGSNGQL
6     S          LINRQLGRNRSDTDLSKWLWMLP________
7     S          TQIPGTQTESRAEELSPAALSPSLEPIRCSH
8     S          TQTESRAEELSPAALSPSLEPIRCSHQPISL
9     S          TESRAEELSPAALSPSLEPIRCSHQPISLLG
10    S          RQPEKPSHLHLEKASSWPHRRDSGRPPGDSS
11    S          _____MEAEEAQRGASPPISAIEEFSIIPEA
12    S          SQQRLESLSETPGPSSPRQPRKALVSSESYL
13    S          STGTVQHLRSDSFPGSHRTEQTPDLVGMLLS
14    S          WLVKSGELTALEFSASPGLRRKLNTRPVHLH
15    S          CQDWTVPLPASAGRTSWPPATARSTESFTST
16    S          LRRTTPQQGASGPGRSPVGQARQPEKPSHLH
17    S          EEETSSDNSGQTRYYSPCEEHPAETNQNEGS
18    S          ENDKEYQEYLKRPPESPPIVEEWNSRAGGNQ
19    S          SSTDPRPRDWRGPPNSPDLKLSDSDIPGSSE
20    S          RHSPAPPPDPGFPAPSPPPADSPSEGFSLKA
21    S          PPRRAETFAGYDCTNSPTKNGSFKKKVSSTD
22    S          NKLMGKDESTSRNRRSLSPILPGRHSPAPPP
23    S          LMGKDESTSRNRRSLSPILPGRHSPAPPPDP
24    S          KGGKSRGSQRWESSASFDLKQQLLLNKLMGK
25    S          GAESILSGKENSSALSPNHRIYSSPIAGVIP
26    S          IKLVKSIESDRRKINSAPSSPIKTNKAESSQ
27    S          VKSIESDRRKINSAPSSPIKTNKAESSQNSA
28    S          KSIESDRRKINSAPSSPIKTNKAESSQNSAP
29    S          GTGSTNKNLPIMSTASVEIDDALYSRQRYVL
30    S          LLASPGHISVKEPTPSIASDISLPIATQELR
⋮     ⋮          ⋮
20206 Y          PRPSSSNMKRAASLNYLNQPSAAPLQVSRGL
20207 Y          KRSRSRSPHEAGFCVYLKGLPFEAENKHVID
20208 Y          DRMKESSPSGSKSQRYSGAYGASVSDEELKR
20209 Y          ARAVPGSIKRTASVEYKGDGGRHPGDEAANG

In [27]:
de <- read_xlsx(xlsx, sheet="Supplemental_table_S5_G12Ci_Pho")
de

      id    phos.name     logFC         AveExpr      t             P.Value
1      9427 TWISTNB S316  -1.4630784    -0.3534941   -11.619207    1.712724e-15
2      7075 NCBP1 S22     -1.3484388    -0.3635381   -10.928885    1.447706e-14
3     20416 TCF20 S1335   -1.3312265    -0.2877555   -11.865290    1.323597e-14
4     24752 TCOF1 T983    -1.0866286    -0.2844263   -10.370678    8.504164e-14
5     12115 NUFIP2 S629   -0.8626781    -0.2249385   -10.199728    1.474096e-13
6     13475 TNS4 S350     -1.9078550    -0.7506798   -11.879627    3.508940e-13
7      1381 AKAP10 S187   -0.6507479    -0.2310063    -9.834485    4.832369e-13
8     22104 NOC2L S56     -0.9724987    -0.2857339    -9.713469    7.187002e-13
9      7771 TCOF1 S381    -0.7816613    -0.2803066    -9.669709    8.299834e-13
10    20933 MKL2 S66      -1.0981264    -0.2550672    -9.666227    8.395519e-13
11    13720 OXR1 S204     -1.3505976    -0.5007320   -11.274700    1.344910e-12
12    10635 RNF219 S210   -1.2189979    -0.3150012    -9.398288    2.037149e-12
13    10077 ZC3H13 S993   -0.6755473    -0.1583351    -9.370136    2.237073e-12
14    23507 RB1 T356      -1.1225711    -0.3259637    -9.347970    2.408344e-12
15     3989 NF1 S2597     -0.5739731    -0.1755213    -9.333354    2.528467e-12
16    14480 RB1CC1 S644    0.9304306     0.2396452     9.265969    3.165574e-12
17     7770 TCOF1 S906    -0.9220662    -0.3099168    -9.253284    3.302545e-12
18    22687 MORC2 S725    -1.0959703    -0.3038473    -9.243199    3.415695e-12
19    18433 ESF1 S153     -1.0190710    -0.3561533    -9.654667    5.933507e-12
20    22907 POM121C T497  -1.6608579    -0.3066628   -10.683090    5.228007e-12
21    15445 OSTF1 S213     0.5774338     0.1486802     9.017157    7.289307e-12
22    10160 KIAA1217 S361  0.6347837     0.3398823     9.560064    7.814528e-12
23     5385 PXN S106      -0.6971846    -0.2164960    -8.979046    8.287562e-12
24      497 DNM1L S616    -0.6265131    -0.1478481    -8.953870    9.021618e-12
25      716 EI24 S326     -0.9773659    -0.2866020    -8.910372    1.044802e-11
26    14022 EHBP1 S759    -0.9575741    -0.3542038   -10.291716    1.315229e-11
27    14951 PALLD S893    -1.4731848    -0.4267116   -10.302776    1.281036e-11
28    25595 ZNF574 T152   -0.9233083    -0.3740953   -10.146749    1.860303e-11
29    14920 ATXN2L S111   -1.0006944    -0.3010948    -8.784008    1.602176e-11
30    12446 NOP9 S7       -0.9304942    -0.2576167    -8.777911    1.635637e-11
⋮     ⋮     ⋮             ⋮             ⋮            ⋮             ⋮
49241 27634 MYRF T162      1.117537e-03  0.001612318  5.991832e-03 0.9952945
49242 16440 ALS2 S492     -7.324002e-04 -0.020445392 -5.956301e-03 0.9953224
49243  2145 WDHD1 S383    -6.591056e-04 -0.065363645 -5.384059e-03 0.9958127
49244 24985 UBXN2B T59     5.753427e-04  0.039673679  5.349940e-03 0.9957986
49245 26044 FNBP4 T517    -5.108743e-04 -0.012901088 -4.812867e-03 0.9962203
49246 17573 KIAA1671 S402 -6.897690e-04  0.106469469 -4.767414e-03 0.9962560
49247  7808 GOLGA4 S266    4.456427e-04 -0.147451898  4.473403e-03 0.9964869
49248 19371 STAU2 S486     4.773962e-04  0.043149311  4.217821e-03 0.9966876
49249 11603 KDM7A S604    -4.742114e-04 -0.012786182 -4.169621e-03 0.9967255
49250 19182 DDX21 S171    -4.396585e-04 -0.080135794 -4.140271e-03 0.9967485
49251 19183 DDX21 S173    -4.396585e-04 -0.080135794 -4.140271e-03 0.9967485
49252 24220 CDK7 T170      4.902603e-04 -0.053090557  3.647719e-03 0.9971354
49253 12289 RBBP6 S861    -3.241420e-04  0.045534831 -3.294748e-03 0.9974125
49254  2324 PHF14 S208    -3.143377e-04  0.002627545 -3.060228e-03 0.9976200
49255 14281 CDC26 S42      2.785063e-04 -0.102948765  2.671007e-03 0.9979024
49256 27645 SIK3 T469      8.113404e-04 -0.130270012  2.343518e-03 0.9981774
49257  5755 MECP2 S360    -2.285940e-04  0.108815059 -1.700159e-03 0.9986648
49258  2805 BAG2 S20       3.982930e-04 -0.042826030  1.681559e-03 0.9986794
49259  1530 SIPA1L3 S172  -2.219249e-04  0.055311551 -1.635971e-03 0.9987152
49260 11857 SSH2 S1217     1.359547e-04  0.016259009  1.479328e-03 0.9988495
49261  4280 MARK3 S419    -1.261529e-04  0.074402820 -1.023589e-03 0.9992039
49262 23608 TPR T2137     -1.542345e-04  0.001958310 -9.910526e-04 0.9992217
49263  1053 WDR46 S41     -1.045650e-04  0.034653638 -9.370277e-04 0.9992713
49264  6441 HDLBP S756    -1.228581e-04 -0.044826474 -5.687369e-04 0.9995534
49265 10899 IQSEC1 S400   -6.841688e-05  0.071519729 -4.389629e-04 0.9996586
49266 21248 MACF1 S3927   -7.151486e-05 -0.078889195 -4.218589e-04 0.9996719
49267  8957 MED1 S1192    -5.592185e-05 -0.010771939 -3.617726e-04 0.9997159
49268  3930 LMNB1 S404     1.000226e-04  0.050600093  2.441005e-04 0.9998083
49269 10840 ARHGAP17 S575  1.529564e-05 -0.027177359  1.742502e-04 0.9998632
49270  1272 ADCY6 S54      8.696067e-06  0.161763585  4.486329e-05 0.9999648
      adj.P.Val    B         Comparison  time cell.line
1     2.839353e-11 24.95563  G12CivsDMSO 24h  all
2     8.000023e-11 22.90524  G12CivsDMSO 24h  all
3     8.000023e-11 22.76477  G12CivsDMSO 24h  all
4     3.524551e-10 21.19893  G12CivsDMSO 24h  all
5     4.887512e-10 20.66792  G12CivsDMSO 24h  all
6     9.695201e-10 19.63282  G12CivsDMSO 24h  all
7     1.144443e-09 19.52043  G12CivsDMSO 24h  all
8     1.391809e-09 19.13642  G12CivsDMSO 24h  all
9     1.391809e-09 18.99710  G12CivsDMSO 24h  all
10    1.391809e-09 18.98601  G12CivsDMSO 24h  all
11    2.026902e-09 18.40143  G12CivsDMSO 24h  all
12    2.794462e-09 18.12765  G12CivsDMSO 24h  all
13    2.794462e-09 18.03695  G12CivsDMSO 24h  all
14    2.794462e-09 17.96547  G12CivsDMSO 24h  all
15    2.794462e-09 17.91831  G12CivsDMSO 24h  all
16    2.980284e-09 17.70053  G12CivsDMSO 24h  all
17    2.980284e-09 17.65947  G12CivsDMSO 24h  all
18    2.980284e-09 17.62682  G12CivsDMSO 24h  all
19    4.684080e-09 17.15556  G12CivsDMSO 24h  all
20    4.333495e-09 17.14728  G12CivsDMSO 24h  all
21    5.492824e-09 16.89180  G12CivsDMSO 24h  all
22    5.632576e-09 16.88935  G12CivsDMSO 24h  all
23    5.724633e-09 16.76730  G12CivsDMSO 24h  all
24    5.982415e-09 16.68497  G12CivsDMSO 24h  all
25    6.661820e-09 16.54255  G12CivsDMSO 24h  all
26    7.787094e-09 16.46238  G12CivsDMSO 24h  all
27    7.787094e-09 16.31442  G12CivsDMSO 24h  all
28    9.395089e-09 16.12932  G12CivsDMSO 24h  all
29    8.914568e-09 16.12765  G12CivsDMSO 24h  all
30    8.914568e-09 16.10759  G12CivsDMSO 24h  all
⋮     ⋮            ⋮         ⋮           ⋮    ⋮
49241 0.9984269    -6.479959 G12CivsDMSO 24h  SW837
49242 0.9984269    -6.479959 G12CivsDMSO 24h  SW837
49243 0.9986962    -6.479962 G12CivsDMSO 24h  SW837
49244 0.9986962    -6.479963 G12CivsDMSO 24h  SW837
49245 0.9988561    -6.479965 G12CivsDMSO 24h  SW837
49246 0.9988561    -6.479966 G12CivsDMSO 24h  SW837
49247 0.9988561    -6.479967 G12CivsDMSO 24h  SW837
49248 0.9988561    -6.479968 G12CivsDMSO 24h  SW837
49249 0.9988561    -6.479968 G12CivsDMSO 24h  SW837
49250 0.9988561    -6.479969 G12CivsDMSO 24h  SW837
49251 0.9988561    -6.479969 G12CivsDMSO 24h  SW837
49252 0.9991325    -6.479971 G12CivsDMSO 24h  SW837
49253 0.9992991    -6.479972 G12CivsDMSO 24h  SW837
49254 0.9993957    -6.479972 G12CivsDMSO 24h  SW837
49255 0.9995674    -6.479974 G12CivsDMSO 24h  SW837
49256 0.9997317    -6.479975 G12CivsDMSO 24h  SW837
49257 0.9999367    -6.479976 G12CivsDMSO 24h  SW837
49258 0.9999367    -6.479976 G12CivsDMSO 24h  SW837
49259 0.9999367    -6.479976 G12CivsDMSO 24h  SW837
49260 0.9999599    -6.479976 G12CivsDMSO 24h  SW837
49261 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49262 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49263 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49264 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49265 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49266 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49267 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49268 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49269 0.9999648    -6.479977 G12CivsDMSO 24h  SW837
49270 0.9999648    -6.479978 G12CivsDMSO 24h  SW837

In [72]:
meta_proc <- meta %>%
  mutate(
    Position = as.integer(Position),
    
    gene_from_phosname = sub(" [STY][0-9]+$", "", phos.name),
    site_from_phosname = sub("^.* ", "", phos.name),

    phosphosite = site_from_phosname,

    gene_from_fasta = sub(
      ".* GN=([^ ]+).*",
      "\\1",
      Fasta_headers
    ),

    gene_id = ifelse(
      grepl(" GN=", Fasta_headers),
      gene_from_fasta,
      gene_from_phosname
    ),

    protein_id = Uniprot_ID,
      
    site_id = paste(gene_id, protein_id, phosphosite, sep = ":"),

    peptide_id = site_id,
    modified_peptide_sequence = site_id,
    peptide_sequence = site_id,
  ) %>%
  select(
    id,
    phos.name,
    gene_id,
    protein_id,
    phosphosite,
    site_id,
    peptide_id,
    modified_peptide_sequence,
    peptide_sequence,
    Localization_prob,
    PEP,
    Reverse,
    Potential_contaminant
  )

de_int <- de %>%
  left_join(
    meta_proc,
    by = c("id", "phos.name")
  )

In [63]:
meta_proc

      id    phos.name         gene_id  protein_id phosphosite
1      0    MGC50722 S478     CCDC187  A0A096LP49 S478
2      1    TRAV19 S62        TRAV19   A0A0A6YYK7 S62
3      4    LOC102724428 S575 SIK1     A0A0B4J2F2 S575
4      5    LOC102724428 S534 SIK1     A0A0B4J2F2 S534
5      6    GREP1 S508        GREP1    A0A0J9YXV3 S508
6      7    ETDC S52          ETDC     A0A1B0GVM5 S52
7      8    ARHGEF5 S445      ARHGEF5  Q12774     S445
8      9    ARHGEF5 S450      ARHGEF5  Q12774     S450
9     10    ARHGEF5 S452      ARHGEF5  Q12774     S452
10    11    ARHGEF5 S1004     ARHGEF5  Q12774     S1004
11    12    ARHGEF5 S11       ARHGEF5  Q12774     S11
12    14    ARHGEF5 S1126     ARHGEF5  Q12774     S1126
13    16    ARHGEF5 S610      ARHGEF5  Q12774     S610
14    17    ARHGEF5 S1405     ARHGEF5  Q12774     S1405
15    18    ARHGEF5 S897      ARHGEF5  Q12774     S897
16    19    ARHGEF5 S983      ARHGEF5  Q12774     S983
17    20    ARHGEF5 S184      ARHGEF5  Q12774     S184
18    21    FAM103A1 S36      RAMAC    A0A3B3IU46 S36
19    22    ARHGEF18 S694     ARHGEF18 A0A590UK10 S694
20    24    ARHGEF18 S1058    ARHGEF18 A0A590UK10 S1058
21    25    ARHGEF18 S667     ARHGEF18 A0A590UK10 S667
22    26    ARHGEF18 S1035    ARHGEF18 A0A590UK10 S1035
23    27    ARHGEF18 S1037    ARHGEF18 A0A590UK10 S1037
24    28    ARHGEF18 S1010    ARHGEF18 A0A590UK10 S1010
25    29    E2F8 S664         E2F8     A0AVK6     S664
26    30    E2F8 S413         E2F8     A0AVK6     S413
27    31    E2F8 S416         E2F8     A0AVK6     S416
28    32    E2F8 S417         E2F8     A0AVK6     S417
29    33    UBA6 S36          UBA6     A0AVT1     S36
30    34    ESYT2 S755        ESYT2    A0FGR8     S755
⋮     ⋮     ⋮                 ⋮        ⋮          ⋮
20206 28291 KLC4 Y593         KLC4     Q9NSK0     Y593
20207 28292 RBM12 Y433        RBM12    Q9NTZ6     Y433
20208 28294 CHCHD3 Y49        CHCHD3   Q9NX63     Y49
20209 28296 SMPD3 Y212        SMPD3    Q9NY59     Y212
20210 28297 ABI2 Y198         ABI2     Q9NYB9     Y198
20211 28298 BCLAF1 Y383       BCLAF1   Q9NYF8     Y383
20212 28301 BCLAF1 Y284       BCLAF1   Q9NYF8     Y284
20213 28304 CDK12 Y279        CDK12    Q9NYV4     Y279
20214 28309 ITSN2 Y968        ITSN2    Q9NZM3     Y968
20215 28314 SUCO Y1095        SUCO     Q9UBS9     Y1095
20216 28315 TJP2 Y269         TJP2     Q9UDY2     Y269
20217 28316 TJP2 Y1166        TJP2     Q9UDY2     Y1166
20218 28317 TJP2 Y1118        TJP2     Q9UDY2     Y1118
20219 28318 TJP2 Y426         TJP2     Q9UDY2     Y426
20220 28319 TJP2 Y428         TJP2     Q9UDY2     Y428
20221 28321 AFF4 Y712         AFF4     Q9UHB7     Y712
20222 28328 GPATCH8 Y1038     GPATCH8  Q9UKJ3     Y1038
20223 28329 ADAMTS6 Y451      ADAMTS6  Q9UKP5     Y451
20224 28331 ZDHHC8 Y541       ZDHHC8   Q9ULC8     Y541
20225 28334 SNX12 Y72         SNX12    Q9UMY4     Y72
20226 28340 ICK Y159          CILK1    Q9UPZ9     Y159
20227 28341 SRRM2 Y2693       SRRM2    Q9UQ35     Y2693
20228 28342 SRRM2 Y1820       SRRM2    Q9UQ35     Y1820
20229 28346 SCML2 Y506        SCML2    Q9UQR0     Y506
20230 28347 MAP3K2 Y240       MAP3K2   Q9Y2U5     Y240
20231 28348 THRAP3 Y873       THRAP3   Q9Y2W1     Y873
20232 28351 WBP11 Y236        WBP11    Q9Y2W2     Y236
20233 28352 GIT1 Y598         GIT1     Q9Y2X7     Y598
20234 28353 PKP3 Y176         PKP3     Q9Y446     Y176
20235 28354 PKP3 Y195         PKP3     Q9Y446     Y195
      site_id                   peptide_id
1     CCDC187:A0A096LP49:S478   CCDC187:A0A096LP49:S478
2     TRAV19:A0A0A6YYK7:S62     TRAV19:A0A0A6YYK7:S62
3     SIK1:A0A0B4J2F2:S575      SIK1:A0A0B4J2F2:S575
4     SIK1:A0A0B4J2F2:S534      SIK1:A0A0B4J2F2:S534
5     GREP1:A0A0J9YXV3:S508     GREP1:A0A0J9YXV3:S508
6     ETDC:A0A1B0GVM5:S52       ETDC:A0A1B0GVM5:S52
7     ARHGEF5:Q12774:S445       ARHGEF5:Q12774:S445
8     ARHGEF5:Q12774:S450       ARHGEF5:Q12774:S450
9     ARHGEF5:Q12774:S452       ARHGEF5:Q12774:S452
10    ARHGEF5:Q12774:S1004      ARHGEF5:Q12774:S1004
11    ARHGEF5:Q12774:S11        ARHGEF5:Q12774:S11
12    ARHGEF5:Q12774:S1126      ARHGEF5:Q12774:S1126
13    ARHGEF5:Q12774:S610       ARHGEF5:Q12774:S610
14    ARHGEF5:Q12774:S1405      ARHGEF5:Q12774:S1405
15    ARHGEF5:Q12774:S897       ARHGEF5:Q12774:S897
16    ARHGEF5:Q12774:S983       ARHGEF5:Q12774:S983
17    ARHGEF5:Q12774:S184       ARHGEF5:Q12774:S184
18    RAMAC:A0A3B3IU46:S36      RAMAC:A0A3B3IU46:S36
19    ARHGEF18:A0A590UK10:S694  ARHGEF18:A0A590UK10:S694
20    ARHGEF18:A0A590UK10:S1058 ARHGEF18:A0A590UK10:S1058
21    ARHGEF18:A0A590UK10:S667  ARHGEF18:A0A590UK10:S667
22    ARHGEF18:A0A590UK10:S1035 ARHGEF18:A0A590UK10:S1035
23    ARHGEF18:A0A590UK10:S1037 ARHGEF18:A0A590UK10:S1037
24    ARHGEF18:A0A590UK10:S1010 ARHGEF18:A0A590UK10:S1010
25    E2F8:A0AVK6:S664          E2F8:A0AVK6:S664
26    E2F8:A0AVK6:S413          E2F8:A0AVK6:S413
27    E2F8:A0AVK6:S416          E2F8:A0AVK6:S416
28    E2F8:A0AVK6:S417          E2F8:A0AVK6:S417
29    UBA6:A0AVT1:S36           UBA6:A0AVT1:S36
30    ESYT2:A0FGR8:S755         ESYT2:A0FGR8:S755
⋮     ⋮                         ⋮
20206 KLC4:Q9NSK0:Y593          KLC4:Q9NSK0:Y593
20207 RBM12:Q9NTZ6:Y433         RBM12:Q9NTZ6:Y433
20208 CHCHD3:Q9NX63:Y49         CHCHD3:Q9NX63:Y49
20209 SMPD3:Q9NY59:Y212         SMPD3:Q9NY59:Y212
20210 ABI2:Q9NYB9:Y198          ABI2:Q9NYB9:Y198
20211 BCLAF1:Q9NYF8:Y383        BCLAF1:Q9NYF8:Y383
20212 BCLAF1:Q9NYF8:Y284        BCLAF1:Q9NYF8:Y284
20213 CDK12:Q9NYV4:Y279         CDK12:Q9NYV4:Y279
20214 ITSN2:Q9NZM3:Y968         ITSN2:Q9NZM3:Y968
20215 SUCO:Q9UBS9:Y1095         SUCO:Q9UBS9:Y1095
20216 TJP2:Q9UDY2:Y269          TJP2:Q9UDY2:Y269
20217 TJP2:Q9UDY2:Y1166         TJP2:Q9UDY2:Y1166
20218 TJP2:Q9UDY2:Y1118         TJP2:Q9UDY2:Y1118
20219 TJP2:Q9UDY2:Y426          TJP2:Q9UDY2:Y426
20220 TJP2:Q9UDY2:Y428          TJP2:Q9UDY2:Y428
20221 AFF4:Q9UHB7:Y712          AFF4:Q9UHB7:Y712
20222 GPATCH8:Q9UKJ3:Y1038      GPATCH8:Q9UKJ3:Y1038
20223 ADAMTS6:Q9UKP5:Y451       ADAMTS6:Q9UKP5:Y451
20224 ZDHHC8:Q9ULC8:Y541        ZDHHC8:Q9ULC8:Y541
20225 SNX12:Q9UMY4:Y72          SNX12:Q9UMY4:Y72
20226 CILK1:Q9UPZ9:Y159         CILK1:Q9UPZ9:Y159
20227 SRRM2:Q9UQ35:Y2693        SRRM2:Q9UQ35:Y2693
20228 SRRM2:Q9UQ35:Y1820        SRRM2:Q9UQ35:Y1820
20229 SCML2:Q9UQR0:Y506         SCML2:Q9UQR0:Y506
20230 MAP3K2:Q9Y2U5:Y240        MAP3K2:Q9Y2U5:Y240
20231 THRAP3:Q9Y2W1:Y873        THRAP3:Q9Y2W1:Y873
20232 WBP11:Q9Y2W2:Y236         WBP11:Q9Y2W2:Y236
20233 GIT1:Q9Y2X7:Y598          GIT1:Q9Y2X7:Y598
20234 PKP3:Q9Y446:Y176          PKP3:Q9Y446:Y176
20235 PKP3:Q9Y446:Y195          PKP3:Q9Y446:Y195
      modified_peptide_sequence peptide_sequence          Localization_prob
1     CCDC187:A0A096LP49:S478   CCDC187:A0A096LP49:S478   0.997241
2     TRAV19:A0A0A6YYK7:S62     TRAV19:A0A0A6YYK7:S62     1.000000
3     SIK1:A0A0B4J2F2:S575      SIK1:A0A0B4J2F2:S575      0.911043
4     SIK1:A0A0B4J2F2:S534      SIK1:A0A0B4J2F2:S534      0.973662
5     GREP1:A0A0J9YXV3:S508     GREP1:A0A0J9YXV3:S508     1.000000
6     ETDC:A0A1B0GVM5:S52       ETDC:A0A1B0GVM5:S52       0.897359
7     ARHGEF5:Q12774:S445       ARHGEF5:Q12774:S445       0.999999
8     ARHGEF5:Q12774:S450       ARHGEF5:Q12774:S450       0.998142
9     ARHGEF5:Q12774:S452       ARHGEF5:Q12774:S452       0.843071
10    ARHGEF5:Q12774:S1004      ARHGEF5:Q12774:S1004      0.969092
11    ARHGEF5:Q12774:S11        ARHGEF5:Q12774:S11        0.999578
12    ARHGEF5:Q12774:S1126      ARHGEF5:Q12774:S1126      0.967038
13    ARHGEF5:Q12774:S610       ARHGEF5:Q12774:S610       0.851435
14    ARHGEF5:Q12774:S1405      ARHGEF5:Q12774:S1405      0.999896
15    ARHGEF5:Q12774:S897       ARHGEF5:Q12774:S897       0.925109
16    ARHGEF5:Q12774:S983       ARHGEF5:Q12774:S983       0.999988
17    ARHGEF5:Q12774:S184       ARHGEF5:Q12774:S184       0.792286
18    RAMAC:A0A3B3IU46:S36      RAMAC:A0A3B3IU46:S36      1.000000
19    ARHGEF18:A0A590UK10:S694  ARHGEF18:A0A590UK10:S694  1.000000
20    ARHGEF18:A0A590UK10:S1058 ARHGEF18:A0A590UK10:S1058 0.998571
21    ARHGEF18:A0A590UK10:S667  ARHGEF18:A0A590UK10:S667  0.992669
22    ARHGEF18:A0A590UK10:S1035 ARHGEF18:A0A590UK10:S1035 0.841727
23    ARHGEF18:A0A590UK10:S1037 ARHGEF18:A0A590UK10:S1037 0.979681
24    ARHGEF18:A0A590UK10:S1010 ARHGEF18:A0A590UK10:S1010 0.970807
25    E2F8:A0AVK6:S664          E2F8:A0AVK6:S664          0.999658
26    E2F8:A0AVK6:S413          E2F8:A0AVK6:S413          0.963104
27    E2F8:A0AVK6:S416          E2F8:A0AVK6:S416          0.836432
28    E2F8:A0AVK6:S417          E2F8:A0AVK6:S417          0.932842
29    UBA6:A0AVT1:S36           UBA6:A0AVT1:S36           0.999409
30    ESYT2:A0FGR8:S755         ESYT2:A0FGR8:S755         0.928956
⋮     ⋮                         ⋮                         ⋮
20206 KLC4:Q9NSK0:Y593          KLC4:Q9NSK0:Y593          0.859742
20207 RBM12:Q9NTZ6:Y433         RBM12:Q9NTZ6:Y433         0.999993
20208 CHCHD3:Q9NX63:Y49         CHCHD3:Q9NX63:Y49         0.792279
20209 SMPD3:Q9NY59:Y212         SMPD3:Q9NY59:Y212         0.941465
20210 ABI2:Q9NYB9:Y198          ABI2:Q9NYB9:Y198          0.885321
20211 BCLAF1:Q9NYF8:Y383        BCLAF1:Q9NYF8:Y383        0.971023
20212 BCLAF1:Q9NYF8:Y284        BCLAF1:Q9NYF8:Y284        0.837241
20213 CDK12:Q9NYV4:Y279         CDK12:Q9NYV4:Y279         0.959968
20214 ITSN2:Q9NZM3:Y968         ITSN2:Q9NZM3:Y968         1.000000
20215 SUCO:Q9UBS9:Y1095         SUCO:Q9UBS9:Y1095         0.875274
20216 TJP2:Q9UDY2:Y269          TJP2:Q9UDY2:Y269          0.991312
20217 TJP2:Q9UDY2:Y1166         TJP2:Q9UDY2:Y1166         0.920735
20218 TJP2:Q9UDY2:Y1118         TJP2:Q9UDY2:Y1118         1.000000
20219 TJP2:Q9UDY2:Y426          TJP2:Q9UDY2:Y426          0.908236
20220 TJP2:Q9UDY2:Y428          TJP2:Q9UDY2:Y428          0.874390
20221 AFF4:Q9UHB7:Y712          AFF4:Q9UHB7:Y712          0.993673
20222 GPATCH8:Q9UKJ3:Y1038      GPATCH8:Q9UKJ3:Y1038      0.988405
20223 ADAMTS6:Q9UKP5:Y451       ADAMTS6:Q9UKP5:Y451       0.994230
20224 ZDHHC8:Q9ULC8:Y541        ZDHHC8:Q9ULC8:Y541        0.997913
20225 SNX12:Q9UMY4:Y72          SNX12:Q9UMY4:Y72          0.807526
20226 CILK1:Q9UPZ9:Y159         CILK1:Q9UPZ9:Y159         0.994234
20227 SRRM2:Q9UQ35:Y2693        SRRM2:Q9UQ35:Y2693        0.767399
20228 SRRM2:Q9UQ35:Y1820        SRRM2:Q9UQ35:Y1820        0.960688
20229 SCML2:Q9UQR0:Y506         SCML2:Q9UQR0:Y506         0.849832
20230 MAP3K2:Q9Y2U5:Y240        MAP3K2:Q9Y2U5:Y240        0.758833
20231 THRAP3:Q9Y2W1:Y873        THRAP3:Q9Y2W1:Y873        0.827708
20232 WBP11:Q9Y2W2:Y236         WBP11:Q9Y2W2:Y236         0.838354
20233 GIT1:Q9Y2X7:Y598          GIT1:Q9Y2X7:Y598          0.920086
20234 PKP3:Q9Y446:Y176          PKP3:Q9Y446:Y176          0.999525
20235 PKP3:Q9Y446:Y195          PKP3:Q9Y446:Y195          0.793883
      PEP          Reverse Potential_contaminant
1      5.69872e-04 NA      NA
2      5.92316e-03 NA      NA
3      1.40435e-05 NA      NA
4      4.15665e-10 NA      NA
5      2.29371e-02 NA      NA
6      6.22036e-02 NA      NA
7      3.19872e-36 NA      NA
8     3.79655e-115 NA      NA
9      1.03232e-35 NA      NA
10     2.47336e-03 NA      NA
11     3.95583e-68 NA      NA
12     8.99449e-69 NA      NA
13     4.50034e-03 NA      NA
14     2.60530e-30 NA      NA
15     1.02734e-04 NA      NA
16     2.62192e-46 NA      NA
17     4.59284e-19 NA      NA
18     1.54620e-27 NA      NA
19     4.29622e-03 NA      NA
20     1.40891e-15 NA      NA
21     2.82502e-28 NA      NA
22     4.34209e-07 NA      NA
23     4.13623e-05 NA      NA
24     2.36061e-03 NA      NA
25     1.09572e-06 NA      NA
26     3.99080e-03 NA      NA
27     3.99080e-03 NA      NA
28     9.30401e-06 NA      NA
29     1.04529e-57 NA      NA
30     5.23454e-49 NA      NA
⋮     ⋮            ⋮       ⋮
20206 7.18294e-182 NA      NA
20207  4.89969e-09 NA      NA
20208  9.14234e-52 NA      NA
20209  3.56868e-02 NA      NA
20210  1.52844e-04 NA      NA
20211 1.48798e-150 NA      NA
20212  3.40215e-38 NA      NA
20213  5.76533e-03 NA      NA
20214  3.65987e-14 NA      NA
20215  6.10910e-08 NA      NA
20216  4.16738e-03 NA      NA
20217  2.21900e-56 NA      NA
20218  1.58068e-03 NA      NA
20219  1.63791e-19 NA      NA
20220  1.91694e-24 NA      NA
20221  2.97151e-05 NA      NA
20222  2.83436e-04 NA      NA
20223  2.73825e-02 NA      NA
20224  1.02049e-03 NA      NA
20225  5.86676e-03 NA      NA
20226  1.20407e-09 NA      NA
20227  5.36180e-05 NA      NA
20228  2.29870e-11 NA      NA
20229  2.68967e-04 NA      NA
20230  7.22347e-66 NA      NA
20231  3.69459e-06 NA      NA
20232  1.78821e-14 NA      NA
20233  1.17239e-40 NA      NA
20234  3.26750e-05 NA      NA
20235  1.32718e-13 NA      NA

In [35]:
de_int

      id    phos.name     logFC         AveExpr      t             P.Value
1      9427 TWISTNB S316  -1.4630784    -0.3534941   -11.619207    1.712724e-15
2      7075 NCBP1 S22     -1.3484388    -0.3635381   -10.928885    1.447706e-14
3     20416 TCF20 S1335   -1.3312265    -0.2877555   -11.865290    1.323597e-14
4     24752 TCOF1 T983    -1.0866286    -0.2844263   -10.370678    8.504164e-14
5     12115 NUFIP2 S629   -0.8626781    -0.2249385   -10.199728    1.474096e-13
6     13475 TNS4 S350     -1.9078550    -0.7506798   -11.879627    3.508940e-13
7      1381 AKAP10 S187   -0.6507479    -0.2310063    -9.834485    4.832369e-13
8     22104 NOC2L S56     -0.9724987    -0.2857339    -9.713469    7.187002e-13
9      7771 TCOF1 S381    -0.7816613    -0.2803066    -9.669709    8.299834e-13
10    20933 MKL2 S66      -1.0981264    -0.2550672    -9.666227    8.395519e-13
11    13720 OXR1 S204     -1.3505976    -0.5007320   -11.274700    1.344910e-12
12    10635 RNF219 S210   -1.2189979    -0.3150012    -9.398288    2.037149e-12
13    10077 ZC3H13 S993   -0.6755473    -0.1583351    -9.370136    2.237073e-12
14    23507 RB1 T356      -1.1225711    -0.3259637    -9.347970    2.408344e-12
15     3989 NF1 S2597     -0.5739731    -0.1755213    -9.333354    2.528467e-12
16    14480 RB1CC1 S644    0.9304306     0.2396452     9.265969    3.165574e-12
17     7770 TCOF1 S906    -0.9220662    -0.3099168    -9.253284    3.302545e-12
18    22687 MORC2 S725    -1.0959703    -0.3038473    -9.243199    3.415695e-12
19    18433 ESF1 S153     -1.0190710    -0.3561533    -9.654667    5.933507e-12
20    22907 POM121C T497  -1.6608579    -0.3066628   -10.683090    5.228007e-12
21    15445 OSTF1 S213     0.5774338     0.1486802     9.017157    7.289307e-12
22    10160 KIAA1217 S361  0.6347837     0.3398823     9.560064    7.814528e-12
23     5385 PXN S106      -0.6971846    -0.2164960    -8.979046    8.287562e-12
24      497 DNM1L S616    -0.6265131    -0.1478481    -8.953870    9.021618e-12
25      716 EI24 S326     -0.9773659    -0.2866020    -8.910372    1.044802e-11
26    14022 EHBP1 S759    -0.9575741    -0.3542038   -10.291716    1.315229e-11
27    14951 PALLD S893    -1.4731848    -0.4267116   -10.302776    1.281036e-11
28    25595 ZNF574 T152   -0.9233083    -0.3740953   -10.146749    1.860303e-11
29    14920 ATXN2L S111   -1.0006944    -0.3010948    -8.784008    1.602176e-11
30    12446 NOP9 S7       -0.9304942    -0.2576167    -8.777911    1.635637e-11
⋮     ⋮     ⋮             ⋮             ⋮            ⋮             ⋮
49241 27634 MYRF T162      1.117537e-03  0.001612318  5.991832e-03 0.9952945
49242 16440 ALS2 S492     -7.324002e-04 -0.020445392 -5.956301e-03 0.9953224
49243  2145 WDHD1 S383    -6.591056e-04 -0.065363645 -5.384059e-03 0.9958127
49244 24985 UBXN2B T59     5.753427e-04  0.039673679  5.349940e-03 0.9957986
49245 26044 FNBP4 T517    -5.108743e-04 -0.012901088 -4.812867e-03 0.9962203
49246 17573 KIAA1671 S402 -6.897690e-04  0.106469469 -4.767414e-03 0.9962560
49247  7808 GOLGA4 S266    4.456427e-04 -0.147451898  4.473403e-03 0.9964869
49248 19371 STAU2 S486     4.773962e-04  0.043149311  4.217821e-03 0.9966876
49249 11603 KDM7A S604    -4.742114e-04 -0.012786182 -4.169621e-03 0.9967255
49250 19182 DDX21 S171    -4.396585e-04 -0.080135794 -4.140271e-03 0.9967485
49251 19183 DDX21 S173    -4.396585e-04 -0.080135794 -4.140271e-03 0.9967485
49252 24220 CDK7 T170      4.902603e-04 -0.053090557  3.647719e-03 0.9971354
49253 12289 RBBP6 S861    -3.241420e-04  0.045534831 -3.294748e-03 0.9974125
49254  2324 PHF14 S208    -3.143377e-04  0.002627545 -3.060228e-03 0.9976200
49255 14281 CDC26 S42      2.785063e-04 -0.102948765  2.671007e-03 0.9979024
49256 27645 SIK3 T469      8.113404e-04 -0.130270012  2.343518e-03 0.9981774
49257  5755 MECP2 S360    -2.285940e-04  0.108815059 -1.700159e-03 0.9986648
49258  2805 BAG2 S20       3.982930e-04 -0.042826030  1.681559e-03 0.9986794
49259  1530 SIPA1L3 S172  -2.219249e-04  0.055311551 -1.635971e-03 0.9987152
49260 11857 SSH2 S1217     1.359547e-04  0.016259009  1.479328e-03 0.9988495
49261  4280 MARK3 S419    -1.261529e-04  0.074402820 -1.023589e-03 0.9992039
49262 23608 TPR T2137     -1.542345e-04  0.001958310 -9.910526e-04 0.9992217
49263  1053 WDR46 S41     -1.045650e-04  0.034653638 -9.370277e-04 0.9992713
49264  6441 HDLBP S756    -1.228581e-04 -0.044826474 -5.687369e-04 0.9995534
49265 10899 IQSEC1 S400   -6.841688e-05  0.071519729 -4.389629e-04 0.9996586
49266 21248 MACF1 S3927   -7.151486e-05 -0.078889195 -4.218589e-04 0.9996719
49267  8957 MED1 S1192    -5.592185e-05 -0.010771939 -3.617726e-04 0.9997159
49268  3930 LMNB1 S404     1.000226e-04  0.050600093  2.441005e-04 0.9998083
49269 10840 ARHGAP17 S575  1.529564e-05 -0.027177359  1.742502e-04 0.9998632
49270  1272 ADCY6 S54      8.696067e-06  0.161763585  4.486329e-05 0.9999648
      adj.P.Val    B         Comparison  time ⋯ protein_id phosphosite
1     2.839353e-11 24.95563  G12CivsDMSO 24h  ⋯ Q3B726     S316
2     8.000023e-11 22.90524  G12CivsDMSO 24h  ⋯ Q09161     S22
3     8.000023e-11 22.76477  G12CivsDMSO 24h  ⋯ Q9UGU0     S1335
4     3.524551e-10 21.19893  G12CivsDMSO 24h  ⋯ Q13428     T983
5     4.887512e-10 20.66792  G12CivsDMSO 24h  ⋯ Q7Z417     S629
6     9.695201e-10 19.63282  G12CivsDMSO 24h  ⋯ Q8IZW8     S350
7     1.144443e-09 19.52043  G12CivsDMSO 24h  ⋯ O43572     S187
8     1.391809e-09 19.13642  G12CivsDMSO 24h  ⋯ Q9Y3T9     S56
9     1.391809e-09 18.99710  G12CivsDMSO 24h  ⋯ Q13428     S381
10    1.391809e-09 18.98601  G12CivsDMSO 24h  ⋯ Q9ULH7     S66
11    2.026902e-09 18.40143  G12CivsDMSO 24h  ⋯ Q8N573     S204
12    2.794462e-09 18.12765  G12CivsDMSO 24h  ⋯ Q5W0B1     S210
13    2.794462e-09 18.03695  G12CivsDMSO 24h  ⋯ Q5T200     S993
14    2.794462e-09 17.96547  G12CivsDMSO 24h  ⋯ P06400     T356
15    2.794462e-09 17.91831  G12CivsDMSO 24h  ⋯ P21359     S2597
16    2.980284e-09 17.70053  G12CivsDMSO 24h  ⋯ Q8TDY2     S644
17    2.980284e-09 17.65947  G12CivsDMSO 24h  ⋯ Q13428     S906
18    2.980284e-09 17.62682  G12CivsDMSO 24h  ⋯ Q9Y6X9     S725
19    4.684080e-09 17.15556  G12CivsDMSO 24h  ⋯ Q9H501     S153
20    4.333495e-09 17.14728  G12CivsDMSO 24h  ⋯ Q96HA1     T497
21    5.492824e-09 16.89180  G12CivsDMSO 24h  ⋯ Q92882     S213
22    5.632576e-09 16.88935  G12CivsDMSO 24h  ⋯ Q5T5P2     S361
23    5.724633e-09 16.76730  G12CivsDMSO 24h  ⋯ P49023     S106
24    5.982415e-09 16.68497  G12CivsDMSO 24h  ⋯ O00429     S616
25    6.661820e-09 16.54255  G12CivsDMSO 24h  ⋯ O14681     S326
26    7.787094e-09 16.46238  G12CivsDMSO 24h  ⋯ Q8NDI1     S759
27    7.787094e-09 16.31442  G12CivsDMSO 24h  ⋯ Q8WX93     S893
28    9.395089e-09 16.12932  G12CivsDMSO 24h  ⋯ Q6ZN55     T152
29    8.914568e-09 16.12765  G12CivsDMSO 24h  ⋯ Q8WWM7     S111
30    8.914568e-09 16.10759  G12CivsDMSO 24h  ⋯ Q86U38     S7
⋮     ⋮            ⋮         ⋮           ⋮    ⋱ ⋮          ⋮
49241 0.9984269    -6.479959 G12CivsDMSO 24h  ⋯ Q9Y2G1     T162
49242 0.9984269    -6.479959 G12CivsDMSO 24h  ⋯ Q96Q42     S492
49243 0.9986962    -6.479962 G12CivsDMSO 24h  ⋯ O75717     S383
49244 0.9986962    -6.479963 G12CivsDMSO 24h  ⋯ Q14CS0     T59
49245 0.9988561    -6.479965 G12CivsDMSO 24h  ⋯ Q8N3X1     T517
49246 0.9988561    -6.479966 G12CivsDMSO 24h  ⋯ Q9BY89     S402
49247 0.9988561    -6.479967 G12CivsDMSO 24h  ⋯ Q13439     S266
49248 0.9988561    -6.479968 G12CivsDMSO 24h  ⋯ Q9NUL3     S486
49249 0.9988561    -6.479968 G12CivsDMSO 24h  ⋯ Q6ZMT4     S604
49250 0.9988561    -6.479969 G12CivsDMSO 24h  ⋯ Q9NR30     S171
49251 0.9988561    -6.479969 G12CivsDMSO 24h  ⋯ Q9NR30     S173
49252 0.9991325    -6.479971 G12CivsDMSO 24h  ⋯ P50613     T170
49253 0.9992991    -6.479972 G12CivsDMSO 24h  ⋯ Q7Z6E9     S861
49254 0.9993957    -6.479972 G12CivsDMSO 24h  ⋯ O94880     S208
49255 0.9995674    -6.479974 G12CivsDMSO 24h  ⋯ Q8NHZ8     S42
49256 0.9997317    -6.479975 G12CivsDMSO 24h  ⋯ Q9Y2K2     T469
49257 0.9999367    -6.479976 G12CivsDMSO 24h  ⋯ P51608     S360
49258 0.9999367    -6.479976 G12CivsDMSO 24h  ⋯ O95816     S20
49259 0.9999367    -6.479976 G12CivsDMSO 24h  ⋯ O60292     S172
49260 0.9999599    -6.479976 G12CivsDMSO 24h  ⋯ Q76I76     S1217
49261 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ P27448     S419
49262 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ P12270     T2137
49263 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ O15213     S41
49264 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ Q00341     S756
49265 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ Q6DN90     S400
49266 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ Q9UPN3     S3927
49267 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ Q15648     S1192
49268 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ P20700     S404
49269 0.9999648    -6.479977 G12CivsDMSO 24h  ⋯ Q68EM7     S575
49270 0.9999648    -6.479978 G12CivsDMSO 24h  ⋯ O43306     S54
      site_id       peptide_id    modified_peptide_sequence peptide_sequence
1     TWISTNB S316  TWISTNB S316  TWISTNB S316              TWISTNB S316
2     NCBP1 S22     NCBP1 S22     NCBP1 S22                 NCBP1 S22
3     TCF20 S1335   TCF20 S1335   TCF20 S1335               TCF20 S1335
4     TCOF1 T983    TCOF1 T983    TCOF1 T983                TCOF1 T983
5     NUFIP2 S629   NUFIP2 S629   NUFIP2 S629               NUFIP2 S629
6     TNS4 S350     TNS4 S350     TNS4 S350                 TNS4 S350
7     AKAP10 S187   AKAP10 S187   AKAP10 S187               AKAP10 S187
8     NOC2L S56     NOC2L S56     NOC2L S56                 NOC2L S56
9     TCOF1 S381    TCOF1 S381    TCOF1 S381                TCOF1 S381
10    MKL2 S66      MKL2 S66      MKL2 S66                  MKL2 S66
11    OXR1 S204     OXR1 S204     OXR1 S204                 OXR1 S204
12    RNF219 S210   RNF219 S210   RNF219 S210               RNF219 S210
13    ZC3H13 S993   ZC3H13 S993   ZC3H13 S993               ZC3H13 S993
14    RB1 T356      RB1 T356      RB1 T356                  RB1 T356
15    NF1 S2597     NF1 S2597     NF1 S2597                 NF1 S2597
16    RB1CC1 S644   RB1CC1 S644   RB1CC1 S644               RB1CC1 S644
17    TCOF1 S906    TCOF1 S906    TCOF1 S906                TCOF1 S906
18    MORC2 S725    MORC2 S725    MORC2 S725                MORC2 S725
19    ESF1 S153     ESF1 S153     ESF1 S153                 ESF1 S153
20    POM121C T497  POM121C T497  POM121C T497              POM121C T497
21    OSTF1 S213    OSTF1 S213    OSTF1 S213                OSTF1 S213
22    KIAA1217 S361 KIAA1217 S361 KIAA1217 S361             KIAA1217 S361
23    PXN S106      PXN S106      PXN S106                  PXN S106
24    DNM1L S616    DNM1L S616    DNM1L S616                DNM1L S616
25    EI24 S326     EI24 S326     EI24 S326                 EI24 S326
26    EHBP1 S759    EHBP1 S759    EHBP1 S759                EHBP1 S759
27    PALLD S893    PALLD S893    PALLD S893                PALLD S893
28    ZNF574 T152   ZNF574 T152   ZNF574 T152               ZNF574 T152
29    ATXN2L S111   ATXN2L S111   ATXN2L S111               ATXN2L S111
30    NOP9 S7       NOP9 S7       NOP9 S7                   NOP9 S7
⋮     ⋮             ⋮             ⋮                         ⋮
49241 MYRF T162     MYRF T162     MYRF T162                 MYRF T162
49242 ALS2 S492     ALS2 S492     ALS2 S492                 ALS2 S492
49243 WDHD1 S383    WDHD1 S383    WDHD1 S383                WDHD1 S383
49244 UBXN2B T59    UBXN2B T59    UBXN2B T59                UBXN2B T59
49245 FNBP4 T517    FNBP4 T517    FNBP4 T517                FNBP4 T517
49246 KIAA1671 S402 KIAA1671 S402 KIAA1671 S402             KIAA1671 S402
49247 GOLGA4 S266   GOLGA4 S266   GOLGA4 S266               GOLGA4 S266
49248 STAU2 S486    STAU2 S486    STAU2 S486                STAU2 S486
49249 KDM7A S604    KDM7A S604    KDM7A S604                KDM7A S604
49250 DDX21 S171    DDX21 S171    DDX21 S171                DDX21 S171
49251 DDX21 S173    DDX21 S173    DDX21 S173                DDX21 S173
49252 CDK7 T170     CDK7 T170     CDK7 T170                 CDK7 T170
49253 RBBP6 S861    RBBP6 S861    RBBP6 S861                RBBP6 S861
49254 PHF14 S208    PHF14 S208    PHF14 S208                PHF14 S208
49255 CDC26 S42     CDC26 S42     CDC26 S42                 CDC26 S42
49256 SIK3 T469     SIK3 T469     SIK3 T469                 SIK3 T469
49257 MECP2 S360    MECP2 S360    MECP2 S360                MECP2 S360
49258 BAG2 S20      BAG2 S20      BAG2 S20                  BAG2 S20
49259 SIPA1L3 S172  SIPA1L3 S172  SIPA1L3 S172              SIPA1L3 S172
49260 SSH2 S1217    SSH2 S1217    SSH2 S1217                SSH2 S1217
49261 MARK3 S419    MARK3 S419    MARK3 S419                MARK3 S419
49262 TPR T2137     TPR T2137     TPR T2137                 TPR T2137
49263 WDR46 S41     WDR46 S41     WDR46 S41                 WDR46 S41
49264 HDLBP S756    HDLBP S756    HDLBP S756                HDLBP S756
49265 IQSEC1 S400   IQSEC1 S400   IQSEC1 S400               IQSEC1 S400
49266 MACF1 S3927   MACF1 S3927   MACF1 S3927               MACF1 S3927
49267 MED1 S1192    MED1 S1192    MED1 S1192                MED1 S1192
49268 LMNB1 S404    LMNB1 S404    LMNB1 S404                LMNB1 S404
49269 ARHGAP17 S575 ARHGAP17 S575 ARHGAP17 S575             ARHGAP17 S575
49270 ADCY6 S54     ADCY6 S54     ADCY6 S54                 ADCY6 S54
      Localization_prob PEP          Reverse Potential_contaminant
1     0.999901           1.53415e-12 NA      NA
2     0.888501          1.33410e-132 NA      NA
3     0.995432           2.88932e-18 NA      NA
4     0.960687           5.97708e-59 NA      NA
5     0.999811           1.43493e-96 NA      NA
6     0.999288           4.16681e-04 NA      NA
7     0.998339           1.22644e-50 NA      NA
8     0.999957           1.31676e-37 NA      NA
9     1.000000          7.12655e-108 NA      NA
10    1.000000           1.25163e-06 NA      NA
11    0.982196           2.90639e-27 NA      NA
12    1.000000           6.67392e-05 NA      NA
13    1.000000          3.94651e-186 NA      NA
14    0.999933           2.38472e-99 NA      NA
15    0.991017           2.85225e-50 NA      NA
16    0.974551           3.91792e-64 NA      NA
17    1.000000           1.63590e-07 NA      NA
18    0.994836           1.15378e-03 NA      NA
19    0.999836           5.86511e-04 NA      NA
20    0.990954           9.13796e-70 NA      NA
21    1.000000          5.03294e-163 NA      NA
22    0.961855           8.71729e-42 NA      NA
23    0.999999           0.00000e+00 NA      NA
24    0.999996           3.37629e-07 NA      NA
25    1.000000           2.30050e-04 NA      NA
26    0.986904           1.04272e-03 NA      NA
27    0.999886           1.56155e-46 NA      NA
28    0.989222           1.69929e-04 NA      NA
29    1.000000          1.75908e-211 NA      NA
30    1.000000           4.44109e-04 NA      NA
⋮     ⋮                 ⋮            ⋮       ⋮
49241 0.966525           9.89209e-22 NA      NA
49242 1.000000           5.11844e-56 NA      NA
49243 0.999671           1.31307e-06 NA      NA
49244 0.975490           2.79973e-03 NA      NA
49245 0.891753           8.53362e-14 NA      NA
49246 0.999740           1.51478e-03 NA      NA
49247 1.000000          1.29716e-182 NA      NA
49248 0.981869           4.67568e-39 NA      NA
49249 0.991255           2.85246e-08 NA      NA
49250 0.992370           1.42415e-31 NA      NA
49251 0.992370           1.42415e-31 NA      NA
49252 0.998924           3.91283e-05 NA      NA
49253 1.000000           2.13317e-28 NA      NA
49254 0.940153           2.18156e-89 NA      NA
49255 1.000000           3.13888e-62 NA      NA
49256 1.000000           5.37876e-04 NA      NA
49257 0.897825           9.32820e-05 NA      NA
49258 0.999263           2.90876e-03 NA      NA
49259 0.993548           0.00000e+00 NA      NA
49260 0.998707           8.03651e-14 NA      NA
49261 0.896658           3.13780e-07 NA      NA
49262 0.988512           2.24078e-19 NA      NA
49263 0.998861           7.39871e-27 NA      NA
49264 0.966644           2.02801e-03 NA      NA
49265 0.998974           7.47477e-03 NA      NA
49266 0.999511           5.78616e-20 NA      NA
49267 0.891818           1.44758e-10 NA      NA
49268 0.982598           1.16239e-05 NA      NA
49269 0.986335           3.96962e-93 NA      NA
49270 0.997020           1.87866e-50 NA      NA

In [73]:
mvespa_long_t <- de_int %>%
  filter(!is.na(site_id)) %>%
  filter(!is.na(t)) %>%
  filter(is.na(Reverse) | Reverse != "+") %>%
  filter(is.na(Potential_contaminant) | Potential_contaminant != "+") %>%
  mutate(
    condition = paste(cell.line, Comparison, time, sep = "__")
  ) %>%
  select(site_id, condition, t) %>%
  group_by(site_id, condition) %>%
  summarise(
    value = mean(t, na.rm = TRUE),
    .groups = "drop"
  )

mvespa_mat_t <- mvespa_long_t %>%
  pivot_wider(
    names_from = condition,
    values_from = value
  ) %>%
  as.data.frame()

rownames(mvespa_mat_t) <- mvespa_mat_t$site_id
mvespa_mat_t$site_id <- NULL

mvespa_mat_t <- as.matrix(mvespa_mat_t)
storage.mode(mvespa_mat_t) <- "numeric"

dim(mvespa_mat_t)
mvespa_mat_t[1:5, 1:min(5, ncol(mvespa_mat_t))]

[1] 16578     4

                  H358__G12CivsDMSO__24h MIAPACA2__G12CivsDMSO__24h
AAAS:Q9NRG9:S495  1.482185               -1.3156455
AAGAB:Q6PD74:S311       NA                       NA
AAK1:Q2M2I8:S18         NA                1.4765259
AAK1:Q2M2I8:S20   3.774719                       NA
AAK1:Q2M2I8:S21   2.056374                0.9280947
                  SW837__G12CivsDMSO__24h all__G12CivsDMSO__24h
AAAS:Q9NRG9:S495  -0.6464617              -0.2438852
AAGAB:Q6PD74:S311  2.3630937               2.2426104
AAK1:Q2M2I8:S18           NA               1.6795537
AAK1:Q2M2I8:S20    2.1273306               3.2214259
AAK1:Q2M2I8:S21    0.6277044               2.1934061

In [37]:
library <- "./tools/references/library.fasta"
spregulon <- readRDS("./runs/cptac-pdac/vespa.net/results/stdpimeta_substrate_protein_regulon.rds")
aregulon <- readRDS("./runs/cptac-pdac/vespa.net/results/dpimeta_activity_protein_regulon.rds")

Warning message in gzfile(file, "rb"):
“cannot open compressed file './runs/cptac-pdac/vespa.net/results/stdpimeta_substrate_protein_regulon.rds', probable reason 'No such file or directory'”

ERROR: Error in gzfile(file, "rb"): cannot open the connection

In [74]:
new_sites <- unique(mvespa_long_t$site_id)
new_sites <- new_sites[!is.na(new_sites)]

sp_targets <- unique(unlist(lapply(spregulon, function(x) {
  names(x$tfmode)
})))

sp_targets <- sp_targets[!is.na(sp_targets)]

sp_overlap <- intersect(new_sites, sp_targets)

length(sp_overlap)
length(new_sites)
length(sp_targets)

overlap_new_vs_sp <- length(sp_overlap) / length(new_sites)
overlap_sp_vs_new <- length(sp_overlap) / length(sp_targets)

overlap_new_vs_sp
overlap_sp_vs_new

ERROR: Error: object 'spregulon' not found

In [41]:
dvespa_input <- readRDS("./data/cptac-pdac/processed/CPTAC_PDAC_phospho.rds")
dvespa_input

        gene_id   protein_id peptide_id           site_id
1       ACADVL    P49748     ACADVL:P49748:S489   ACADVL:P49748:S489
2       PSEN1     P49768     PSEN1:P49768:S367    PSEN1:P49768:S367
3       ALDOA     P04075     ALDOA:P04075:S132    ALDOA:P04075:S132
4       ALDOA     P04075     ALDOA:P04075:S276    ALDOA:P04075:S276
5       ALDOA     P04075     ALDOA:P04075:S36     ALDOA:P04075:S36
6       ALDOA     P04075     ALDOA:P04075:S39     ALDOA:P04075:S39
7       ALDOA     P04075     ALDOA:P04075:S46     ALDOA:P04075:S46
8       ALDOA     P04075     ALDOA:P04075:T9      ALDOA:P04075:T9
9       ALDOB     P05062     ALDOB:P05062:S161    ALDOB:P05062:S161
10      ANK1      P16157     ANK1:P16157:S1428    ANK1:P16157:S1428
11      ANK1      P16157     ANK1:P16157:S1593    ANK1:P16157:S1593
12      ANK1      P16157     ANK1:P16157:S1686    ANK1:P16157:S1686
13      ANK1      P16157     ANK1:P16157:S4       ANK1:P16157:S4
14      ANK1      P16157     ANK1:P16157:S759     ANK1:P16157:S759
15      ANK1      P16157     ANK1:P16157:S781     ANK1:P16157:S781
16      ANK1      P16157     ANK1:P16157:S834     ANK1:P16157:S834
17      ANK1      P16157     ANK1:P16157:S856     ANK1:P16157:S856
18      ANK1      P16157     ANK1:P16157:T1378    ANK1:P16157:T1378
19      ANK1      P16157     ANK1:P16157:T961     ANK1:P16157:T961
20      APC       P25054     APC:P25054:S111      APC:P25054:S111
21      APC       P25054     APC:P25054:S1343     APC:P25054:S1343
22      APC       P25054     APC:P25054:S1371     APC:P25054:S1371
23      APC       P25054     APC:P25054:S1774     APC:P25054:S1774
24      APC       P25054     APC:P25054:S2260     APC:P25054:S2260
25      APC       P25054     APC:P25054:S2270     APC:P25054:S2270
26      APC       P25054     APC:P25054:S2290     APC:P25054:S2290
27      APC       P25054     APC:P25054:S2323     APC:P25054:S2323
28      APC       P25054     APC:P25054:S2368     APC:P25054:S2368
29      APC       P25054     APC:P25054:S2374     APC:P25054:S2374
30      APC       P25054     APC:P25054:S2449     APC:P25054:S2449
⋮       ⋮         ⋮          ⋮                    ⋮
2272163 FN1       P02751     FN1:P02751:S2475     FN1:P02751:S2475
2272164 PRKCB     P05771     PRKCB:P05771:T642    PRKCB:P05771:T642
2272165 BLOC1S3   Q6QNY0     BLOC1S3:Q6QNY0:S65   BLOC1S3:Q6QNY0:S65
2272166 LYSMD1    Q96S90     LYSMD1:Q96S90:S23    LYSMD1:Q96S90:S23
2272167 LYSMD1    Q96S90     LYSMD1:Q96S90:S99    LYSMD1:Q96S90:S99
2272168 EEF1AKMT2 Q5JPI9     EEF1AKMT2:Q5JPI9:S21 EEF1AKMT2:Q5JPI9:S21
2272169 PKN1      Q16512     PKN1:Q16512:S374     PKN1:Q16512:S374
2272170 PKN1      Q16512     PKN1:Q16512:S562     PKN1:Q16512:S562
2272171 PKN1      Q16512     PKN1:Q16512:S916     PKN1:Q16512:S916
2272172 PKN1      Q16512     PKN1:Q16512:T774     PKN1:Q16512:T774
2272173 RAPH1     Q70E73     RAPH1:Q70E73:S1012   RAPH1:Q70E73:S1012
2272174 RAPH1     Q70E73     RAPH1:Q70E73:S1033   RAPH1:Q70E73:S1033
2272175 RAPH1     Q70E73     RAPH1:Q70E73:S1098   RAPH1:Q70E73:S1098
2272176 RAPH1     Q70E73     RAPH1:Q70E73:S1154   RAPH1:Q70E73:S1154
2272177 RAPH1     Q70E73     RAPH1:Q70E73:S1183   RAPH1:Q70E73:S1183
2272178 RAPH1     Q70E73     RAPH1:Q70E73:S139    RAPH1:Q70E73:S139
2272179 RAPH1     Q70E73     RAPH1:Q70E73:S41     RAPH1:Q70E73:S41
2272180 RAPH1     Q70E73     RAPH1:Q70E73:S54     RAPH1:Q70E73:S54
2272181 RAPH1     Q70E73     RAPH1:Q70E73:S571    RAPH1:Q70E73:S571
2272182 RAPH1     Q70E73     RAPH1:Q70E73:S610    RAPH1:Q70E73:S610
2272183 RAPH1     Q70E73     RAPH1:Q70E73:S845    RAPH1:Q70E73:S845
2272184 RAPH1     Q70E73     RAPH1:Q70E73:S853    RAPH1:Q70E73:S853
2272185 RAPH1     Q70E73     RAPH1:Q70E73:S856    RAPH1:Q70E73:S856
2272186 RAPH1     Q70E73     RAPH1:Q70E73:S894    RAPH1:Q70E73:S894
2272187 RAPH1     Q70E73     RAPH1:Q70E73:S983    RAPH1:Q70E73:S983
2272188 RAPH1     Q70E73     RAPH1:Q70E73:S996    RAPH1:Q70E73:S996
2272189 RAPH1     Q70E73     RAPH1:Q70E73:T1097   RAPH1:Q70E73:T1097
2272190 RAPH1     Q70E73     RAPH1:Q70E73:T805    RAPH1:Q70E73:T805
2272191 RAPH1     Q70E73     RAPH1:Q70E73:T830    RAPH1:Q70E73:T830
2272192 SLC16A12  Q6ZSM3     SLC16A12:Q6ZSM3:S478 SLC16A12:Q6ZSM3:S478
        modified_peptide_sequence peptide_sequence     phosphosite run_id
1       ACADVL:P49748:S489        ACADVL:P49748:S489   S489        C3N-03884
2       PSEN1:P49768:S367         PSEN1:P49768:S367    S367        C3N-03884
3       ALDOA:P04075:S132         ALDOA:P04075:S132    S132        C3N-03884
4       ALDOA:P04075:S276         ALDOA:P04075:S276    S276        C3N-03884
5       ALDOA:P04075:S36          ALDOA:P04075:S36     S36         C3N-03884
6       ALDOA:P04075:S39          ALDOA:P04075:S39     S39         C3N-03884
7       ALDOA:P04075:S46          ALDOA:P04075:S46     S46         C3N-03884
8       ALDOA:P04075:T9           ALDOA:P04075:T9      T9          C3N-03884
9       ALDOB:P05062:S161         ALDOB:P05062:S161    S161        C3N-03884
10      ANK1:P16157:S1428         ANK1:P16157:S1428    S1428       C3N-03884
11      ANK1:P16157:S1593         ANK1:P16157:S1593    S1593       C3N-03884
12      ANK1:P16157:S1686         ANK1:P16157:S1686    S1686       C3N-03884
13      ANK1:P16157:S4            ANK1:P16157:S4       S4          C3N-03884
14      ANK1:P16157:S759          ANK1:P16157:S759     S759        C3N-03884
15      ANK1:P16157:S781          ANK1:P16157:S781     S781        C3N-03884
16      ANK1:P16157:S834          ANK1:P16157:S834     S834        C3N-03884
17      ANK1:P16157:S856          ANK1:P16157:S856     S856        C3N-03884
18      ANK1:P16157:T1378         ANK1:P16157:T1378    T1378       C3N-03884
19      ANK1:P16157:T961          ANK1:P16157:T961     T961        C3N-03884
20      APC:P25054:S111           APC:P25054:S111      S111        C3N-03884
21      APC:P25054:S1343          APC:P25054:S1343     S1343       C3N-03884
22      APC:P25054:S1371          APC:P25054:S1371     S1371       C3N-03884
23      APC:P25054:S1774          APC:P25054:S1774     S1774       C3N-03884
24      APC:P25054:S2260          APC:P25054:S2260     S2260       C3N-03884
25      APC:P25054:S2270          APC:P25054:S2270     S2270       C3N-03884
26      APC:P25054:S2290          APC:P25054:S2290     S2290       C3N-03884
27      APC:P25054:S2323          APC:P25054:S2323     S2323       C3N-03884
28      APC:P25054:S2368          APC:P25054:S2368     S2368       C3N-03884
29      APC:P25054:S2374          APC:P25054:S2374     S2374       C3N-03884
30      APC:P25054:S2449          APC:P25054:S2449     S2449       C3N-03884
⋮       ⋮                         ⋮                    ⋮           ⋮
2272163 FN1:P02751:S2475          FN1:P02751:S2475     S2475       C3N-03069
2272164 PRKCB:P05771:T642         PRKCB:P05771:T642    T642        C3N-03069
2272165 BLOC1S3:Q6QNY0:S65        BLOC1S3:Q6QNY0:S65   S65         C3N-03069
2272166 LYSMD1:Q96S90:S23         LYSMD1:Q96S90:S23    S23         C3N-03069
2272167 LYSMD1:Q96S90:S99         LYSMD1:Q96S90:S99    S99         C3N-03069
2272168 EEF1AKMT2:Q5JPI9:S21      EEF1AKMT2:Q5JPI9:S21 S21         C3N-03069
2272169 PKN1:Q16512:S374          PKN1:Q16512:S374     S374        C3N-03069
2272170 PKN1:Q16512:S562          PKN1:Q16512:S562     S562        C3N-03069
2272171 PKN1:Q16512:S916          PKN1:Q16512:S916     S916        C3N-03069
2272172 PKN1:Q16512:T774          PKN1:Q16512:T774     T774        C3N-03069
2272173 RAPH1:Q70E73:S1012        RAPH1:Q70E73:S1012   S1012       C3N-03069
2272174 RAPH1:Q70E73:S1033        RAPH1:Q70E73:S1033   S1033       C3N-03069
2272175 RAPH1:Q70E73:S1098        RAPH1:Q70E73:S1098   S1098       C3N-03069
2272176 RAPH1:Q70E73:S1154        RAPH1:Q70E73:S1154   S1154       C3N-03069
2272177 RAPH1:Q70E73:S1183        RAPH1:Q70E73:S1183   S1183       C3N-03069
2272178 RAPH1:Q70E73:S139         RAPH1:Q70E73:S139    S139        C3N-03069
2272179 RAPH1:Q70E73:S41          RAPH1:Q70E73:S41     S41         C3N-03069
2272180 RAPH1:Q70E73:S54          RAPH1:Q70E73:S54     S54         C3N-03069
2272181 RAPH1:Q70E73:S571         RAPH1:Q70E73:S571    S571        C3N-03069
2272182 RAPH1:Q70E73:S610         RAPH1:Q70E73:S610    S610        C3N-03069
2272183 RAPH1:Q70E73:S845         RAPH1:Q70E73:S845    S845        C3N-03069
2272184 RAPH1:Q70E73:S853         RAPH1:Q70E73:S853    S853        C3N-03069
2272185 RAPH1:Q70E73:S856         RAPH1:Q70E73:S856    S856        C3N-03069
2272186 RAPH1:Q70E73:S894         RAPH1:Q70E73:S894    S894        C3N-03069
2272187 RAPH1:Q70E73:S983         RAPH1:Q70E73:S983    S983        C3N-03069
2272188 RAPH1:Q70E73:S996         RAPH1:Q70E73:S996    S996        C3N-03069
2272189 RAPH1:Q70E73:T1097        RAPH1:Q70E73:T1097   T1097       C3N-03069
2272190 RAPH1:Q70E73:T805         RAPH1:Q70E73:T805    T805        C3N-03069
2272191 RAPH1:Q70E73:T830         RAPH1:Q70E73:T830    T830        C3N-03069
2272192 SLC16A12:Q6ZSM3:S478      SLC16A12:Q6ZSM3:S478 S478        C3N-03069
        peptide_intensity
1       13.84222
2       18.93493
3       17.19216
4       16.82438
5       23.08933
6       22.97128
7       23.45205
8       16.92633
9       14.07573
10      15.25923
11      20.42945
12      23.37992
13      16.42333
14      15.34238
15      21.87936
16      24.85493
17      16.78279
18      21.74922
19      18.73758
20      18.95188
21      14.99991
22      14.44570
23      18.43286
24      18.88525
25      16.84252
26      20.94936
27      22.04785
28      14.62295
29      19.71409
30      21.67129
⋮       ⋮
2272163 29.99299
2272164 20.05776
2272165 21.33642
2272166 19.85505
2272167 18.51221
2272168 20.32285
2272169 17.45338
2272170 20.21687
2272171 21.93942
2272172 22.63727
2272173 20.40714
2272174 17.58121
2272175 16.85605
2272176 23.41193
2272177 21.65050
2272178 17.80487
2272179 13.53267
2272180 20.28215
2272181 21.77909
2272182 20.44768
2272183 21.89734
2272184 18.15067
2272185 20.32551
2272186 21.98345
2272187 16.71721
2272188 21.72189
2272189 18.34546
2272190 20.11108
2272191 17.84718
2272192 14.74563

In [75]:
dvespa_sites <- unique(dvespa_input$site_id)
dvespa_sites <- dvespa_sites[!is.na(dvespa_sites)]

ov <- intersect(new_sites, dvespa_sites)

data.frame(
  n_new_sites = length(new_sites),
  n_dvespa_sites = length(dvespa_sites),
  n_overlap = length(ov),
  frac_new_sites_in_dvespa = length(ov) / length(new_sites),
  frac_dvespa_sites_in_new = length(ov) / length(dvespa_sites)
)

  n_new_sites n_dvespa_sites n_overlap frac_new_sites_in_dvespa
1 16578       42500          12050     0.7268669
  frac_dvespa_sites_in_new
1 0.2835294